# Part 0: Importing necessary libraries and setting viewing options as necessary

In [1]:
import os
import pandas as pd
import json
import ast

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Part 1: Loading all language files (PbP) into separate files for each language in preparation of creation of cohesive dataset

In [3]:
# --- Configuration ---
# Define the directory where your JSON files are located
json_directory = 'output'

# --- Data Storage ---
# List to store all loaded JSON data, regardless of language
all_json_data = []

# Dictionaries to store data specifically by language
spanish_json_data = []
english_json_data = []
dutch_json_data = []
# You can add more lists here for other languages if needed

# List to store full paths of all found JSON files
file_paths = []

# --- 1. Locate and Filter JSON Files ---
print(f"Searching for JSON files in: '{json_directory}'...")

# Check if the directory exists
if not os.path.exists(json_directory):
    print(f"Error: Directory '{json_directory}' not found. Please ensure it exists and contains your JSON files.")
else:
    # List all files in the specified directory
    for filename in os.listdir(json_directory):
        # Filter for JSON files that match the common naming pattern
        if filename.endswith(".json") and filename.startswith("mlb_play_n_score_"):
            full_file_path = os.path.join(json_directory, filename)
            file_paths.append(full_file_path)

    # Sort file paths to ensure consistent processing order (e.g., by date in filename)
    file_paths.sort()

    print(f"Found {len(file_paths)} relevant JSON files:")
    for path in file_paths:
        print(f"- {path}")

# --- 2. Load and Categorize JSON Data ---
if file_paths:
    print("\nLoading and categorizing JSON data...")
    for file_path in file_paths:
        try:
            # Open file with UTF-8 encoding for robustness
            with open(file_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
                all_json_data.append(data)

                # Categorize data by language based on filename
                if '_spanish_' in file_path:
                    spanish_json_data.append(data)
                elif '_english_' in file_path:
                    english_json_data.append(data)
                elif '_dutch_' in file_path:
                    dutch_json_data.append(data)
                # Add more `elif` conditions here for other languages if they exist in your files

        except json.JSONDecodeError as e:
            print(f"Warning: Could not decode JSON from '{file_path}'. Error: {e}. Skipping this file.")
        except FileNotFoundError:
            print(f"Error: File not found at '{file_path}'. This shouldn't happen after `os.listdir`, but good for robust handling. Skipping.")
        except Exception as e:
            print(f"An unexpected error occurred while reading '{file_path}'. Error: {e}. Skipping this file.")
else:
    print("No JSON files found matching the criteria. Nothing to load.")

# --- 3. Summary of Loaded Data ---
print("\n--- Loading Summary ---")
print(f"Total JSON objects loaded: {len(all_json_data)}")
print(f"Spanish JSON objects loaded: {len(spanish_json_data)}")
print(f"English JSON objects loaded: {len(english_json_data)}")
print(f"Dutch JSON objects loaded: {len(dutch_json_data)}")
# --- 4. Merge Data ---
# Save each language's data into a single JSON file
json.dump(spanish_json_data, open('spanish_data.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=4)
json.dump(english_json_data, open('english_data.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=4)
json.dump(dutch_json_data, open('dutch_data.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=4)

Searching for JSON files in: 'output'...
Found 45 relevant JSON files:
- output/mlb_play_n_score_dutch_20250608.json
- output/mlb_play_n_score_dutch_20250609.json
- output/mlb_play_n_score_dutch_20250610.json
- output/mlb_play_n_score_dutch_20250611.json
- output/mlb_play_n_score_dutch_20250612.json
- output/mlb_play_n_score_dutch_20250613.json
- output/mlb_play_n_score_dutch_20250614.json
- output/mlb_play_n_score_dutch_20250615.json
- output/mlb_play_n_score_dutch_20250616.json
- output/mlb_play_n_score_dutch_20250617.json
- output/mlb_play_n_score_dutch_20250618.json
- output/mlb_play_n_score_dutch_20250619.json
- output/mlb_play_n_score_dutch_20250620.json
- output/mlb_play_n_score_dutch_20250621.json
- output/mlb_play_n_score_dutch_20250622.json
- output/mlb_play_n_score_english_20250608.json
- output/mlb_play_n_score_english_20250609.json
- output/mlb_play_n_score_english_20250610.json
- output/mlb_play_n_score_english_20250611.json
- output/mlb_play_n_score_english_20250612.json
- output/mlb_play_n_score_english_20250613.json
- output/mlb_play_n_score_english_20250614.json
- output/mlb_play_n_score_english_20250615.json
- output/mlb_play_n_score_english_20250616.json
- output/mlb_play_n_score_english_20250617.json
- output/mlb_play_n_score_english_20250618.json
- output/mlb_play_n_score_english_20250619.json
- output/mlb_play_n_score_english_20250620.json
- output/mlb_play_n_score_english_20250621.json
- output/mlb_play_n_score_english_20250622.json
- output/mlb_play_n_score_spanish_20250608.json
- output/mlb_play_n_score_spanish_20250609.json
- output/mlb_play_n_score_spanish_20250610.json
- output/mlb_play_n_score_spanish_20250611.json
- output/mlb_play_n_score_spanish_20250612.json
- output/mlb_play_n_score_spanish_20250613.json
- output/mlb_play_n_score_spanish_20250614.json
- output/mlb_play_n_score_spanish_20250615.json
- output/mlb_play_n_score_spanish_20250616.json
- output/mlb_play_n_score_spanish_20250617.json
- output/mlb_play_n_score_spanish_20250618.json
- output/mlb_play_n_score_spanish_20250619.json
- output/mlb_play_n_score_spanish_20250620.json
- output/mlb_play_n_score_spanish_20250621.json
- output/mlb_play_n_score_spanish_20250622.json

Loading and categorizing JSON data...

--- Loading Summary ---
Total JSON objects loaded: 45
Spanish JSON objects loaded: 15
English JSON objects loaded: 15
Dutch JSON objects loaded: 15

In [4]:
# --- 5. Convert combined data to CSVs ---
# Note: This part is commented out as it requires pandas, which is not imported.
pd.DataFrame(spanish_json_data).to_csv('spanish_data.csv', index=False, encoding='utf-8')
pd.DataFrame(english_json_data).to_csv('english_data.csv', index=False, encoding='utf-8')
pd.DataFrame(dutch_json_data).to_csv('dutch_data.csv', index=False, encoding='utf-8')

In [5]:
# --- 6. Create DataFrames from CSVs ---
# Load the CSV files into pandas DataFrames
spanish_df = pd.read_csv('spanish_data.csv')
english_df = pd.read_csv('english_data.csv')
dutch_df = pd.read_csv('dutch_data.csv')

# --- 7. Display English DataFrame ---
print("\n--- English DataFrame Preview ---")
display(english_df.head())

--- English DataFrame Preview ---

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,"{'game_id': '401695888', 'language': 'english'...","{'game_id': '401695875', 'language': 'english'...","{'game_id': '401695885', 'language': 'english'...","{'game_id': '401695884', 'language': 'english'...","{'game_id': '401695879', 'language': 'english'...","{'game_id': '401695874', 'language': 'english'...","{'game_id': '401695881', 'language': 'english'...","{'game_id': '401695882', 'language': 'english'...","{'game_id': '401695883', 'language': 'english'...","{'game_id': '401695877', 'language': 'english'...","{'game_id': '401695886', 'language': 'english'...","{'game_id': '401695878', 'language': 'english'...","{'game_id': '401695876', 'language': 'english'...","{'game_id': '401764553', 'language': 'english'...","{'game_id': '401695880', 'language': 'english'...",NaN
1,"{'game_id': '401695892', 'language': 'english'...","{'game_id': '401695897', 'language': 'english'...","{'game_id': '401695896', 'language': 'english'...","{'game_id': '401695894', 'language': 'english'...","{'game_id': '401695891', 'language': 'english'...","{'game_id': '401695893', 'language': 'english'...","{'game_id': '401695889', 'language': 'english'...","{'game_id': '401695895', 'language': 'english'...","{'game_id': '401695890', 'language': 'english'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"{'game_id': '401695909', 'language': 'english'...","{'game_id': '401695906', 'language': 'english'...","{'game_id': '401695902', 'language': 'english'...","{'game_id': '401695911', 'language': 'english'...","{'game_id': '401695901', 'language': 'english'...","{'game_id': '401695904', 'language': 'english'...","{'game_id': '401695905', 'language': 'english'...","{'game_id': '401695912', 'language': 'english'...","{'game_id': '401695907', 'language': 'english'...","{'game_id': '401695899', 'language': 'english'...","{'game_id': '401695898', 'language': 'english'...","{'game_id': '401695903', 'language': 'english'...","{'game_id': '401695910', 'language': 'english'...","{'game_id': '401695908', 'language': 'english'...","{'game_id': '401695900', 'language': 'english'...",NaN
3,"{'game_id': '401695916', 'language': 'english'...","{'game_id': '401695921', 'language': 'english'...","{'game_id': '401695914', 'language': 'english'...","{'game_id': '401695915', 'language': 'english'...","{'game_id': '401695920', 'language': 'english'...","{'game_id': '401695922', 'language': 'english'...","{'game_id': '401695925', 'language': 'english'...","{'game_id': '401695913', 'language': 'english'...","{'game_id': '401695924', 'language': 'english'...","{'game_id': '401695919', 'language': 'english'...","{'game_id': '401695926', 'language': 'english'...","{'game_id': '401695927', 'language': 'english'...","{'game_id': '401695917', 'language': 'english'...","{'game_id': '401695923', 'language': 'english'...","{'game_id': '401695918', 'language': 'english'...",NaN
4,"{'game_id': '401695931', 'language': 'english'...","{'game_id': '401695933', 'language': 'english'...","{'game_id': '401695932', 'language': 'english'...","{'game_id': '401695935', 'language': 'english'...","{'game_id': '401695934', 'language': 'english'...","{'game_id': '401695928', 'language': 'english'...","{'game_id': '401695929', 'language': 'english'...","{'game_id': '401695930', 'language': 'english'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Part 2: Cleaning the data from the CSV into a cohesive dataset

In [6]:
# --- Step 1: Combine the three DataFrames into one ---
combined_df = pd.concat([english_df, spanish_df, dutch_df], ignore_index=True)
print("Combined DataFrame created with shape:", combined_df.shape)
# --- Step 2: Process the dataframe to be more informative ---
display(combined_df.head(10))
# --- 1. Extract the first cell in the grid ---
cell = combined_df.iloc[0, 0]
print(f"\nFirst cell in the grid: {cell}")
# --- 2. process the first cell ---
def parse_game_data(json_string):
    """
    Parses a JSON string containing game data into a Python dictionary.

    Args:
        json_string (str): The raw JSON string from the cell.

    Returns:
        dict: A dictionary where keys are the JSON attribute names
              and values are their corresponding data.
    """
    try:
        data = json.loads(json_string)
        return data
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}")
        return None
def parse_literal_dict(literal_string):
    """
    Safely evaluates a string containing a Python literal (like a dictionary).

    Args:
        literal_string (str): The string representation of a Python dictionary.

    Returns:
        dict: The parsed Python dictionary.
    """
    try:
        # ast.literal_eval is safer than eval() for untrusted input
        # and handles Python string representations directly.
        data = ast.literal_eval(literal_string)
        return data
    except (ValueError, SyntaxError) as e:
        print(f"Error evaluating literal string: {e}")
        return None
parsed_df = pd.DataFrame()
list_of_single_row_dfs = []
for i in range(len(combined_df)):
    for j in range(len(combined_df.iloc[0])):
        cell = combined_df.iat[i, j]
        parsed_data = parse_literal_dict(cell)
        if parsed_data:
            # --- 3. make a new DataFrame from the parsed data and append to temporary list---
            list_of_single_row_dfs.append(pd.DataFrame([parsed_data]))
# Combine all single-row DataFrames into one
parsed_df = pd.concat(list_of_single_row_dfs, ignore_index=True)
# --- 4. Print the parsed DataFrame ---
print("\nParsed DataFrame:")
display(parsed_df.head())
pass

Combined DataFrame created with shape: (45, 25)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24
0,"{'game_id': '401695888', 'language': 'english'...","{'game_id': '401695875', 'language': 'english'...","{'game_id': '401695885', 'language': 'english'...","{'game_id': '401695884', 'language': 'english'...","{'game_id': '401695879', 'language': 'english'...","{'game_id': '401695874', 'language': 'english'...","{'game_id': '401695881', 'language': 'english'...","{'game_id': '401695882', 'language': 'english'...","{'game_id': '401695883', 'language': 'english'...","{'game_id': '401695877', 'language': 'english'...","{'game_id': '401695886', 'language': 'english'...","{'game_id': '401695878', 'language': 'english'...","{'game_id': '401695876', 'language': 'english'...","{'game_id': '401764553', 'language': 'english'...","{'game_id': '401695880', 'language': 'english'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"{'game_id': '401695892', 'language': 'english'...","{'game_id': '401695897', 'language': 'english'...","{'game_id': '401695896', 'language': 'english'...","{'game_id': '401695894', 'language': 'english'...","{'game_id': '401695891', 'language': 'english'...","{'game_id': '401695893', 'language': 'english'...","{'game_id': '401695889', 'language': 'english'...","{'game_id': '401695895', 'language': 'english'...","{'game_id': '401695890', 'language': 'english'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"{'game_id': '401695909', 'language': 'english'...","{'game_id': '401695906', 'language': 'english'...","{'game_id': '401695902', 'language': 'english'...","{'game_id': '401695911', 'language': 'english'...","{'game_id': '401695901', 'language': 'english'...","{'game_id': '401695904', 'language': 'english'...","{'game_id': '401695905', 'language': 'english'...","{'game_id': '401695912', 'language': 'english'...","{'game_id': '401695907', 'language': 'english'...","{'game_id': '401695899', 'language': 'english'...","{'game_id': '401695898', 'language': 'english'...","{'game_id': '401695903', 'language': 'english'...","{'game_id': '401695910', 'language': 'english'...","{'game_id': '401695908', 'language': 'english'...","{'game_id': '401695900', 'language': 'english'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"{'game_id': '401695916', 'language': 'english'...","{'game_id': '401695921', 'language': 'english'...","{'game_id': '401695914', 'language': 'english'...","{'game_id': '401695915', 'language': 'english'...","{'game_id': '401695920', 'language': 'english'...","{'game_id': '401695922', 'language': 'english'...","{'game_id': '401695925', 'language': 'english'...","{'game_id': '401695913', 'language': 'english'...","{'game_id': '401695924', 'language': 'english'...","{'game_id': '401695919', 'language': 'english'...","{'game_id': '401695926', 'language': 'english'...","{'game_id': '401695927', 'language': 'english'...","{'game_id': '401695917', 'language': 'english'...","{'game_id': '401695923', 'language': 'english'...","{'game_id': '401695918', 'language': 'english'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"{'game_id': '401695931', 'language': 'english'...","{'game_id': '401695933', 'language': 'english'...","{'game_id': '401695932', 'language': 'english'...","{'game_id': '401695935', 'language': 'english'...","{'game_id': '401695934', 'language': 'english'...","{'game_id': '401695928', 'language': 'english'...","{'game_id': '401695929', 'language': 'english'...","{'game_id': '401695930', 'language': 'english'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"{'game_id': '401695944', 'language': 'english'...","{'game_id': '401695938', 'language': 'english'...","{'game_id': '401695937', 'language': 'english'...","{'game_id': '401695949', 'language': 'english'...","{'game_id': '401695942', 'language': 'english'...","{'game_id': '401695950', 'language': 'english'...","{'game_id': '401695946', 'language': 'english'...","{'game_id': '401695945', 'language': 'english'...","{'game_id': '401695941', 'language': 'english'...","{'game_id': '401695936', 'language': 'english'...","{'game_id': '401695943', 'language': 'english'...","{'game_id': '401695948', 'language': 'english'...","{'game_id': '401695940', 'language': 'english'...","{'game_id': '401695947', 'language': 'english'...","{'game_id': '401695939', 'language': 'english'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"{'game_id': '401695965', 'language': 'english'...","{'game_id': '401695954', 'language': 'english'...","{'game_id': '401695955', 'language': 'english'...","{'game_id': '401695963', 'language': 'english'...","{'game_id': '401695964', 'language': 'english'...","{'game_id': '401695951', 'language': 'english'...","{'game_id': '401695958', 'language': 'english'...","{'game_id': '401695961', 'language': 'english'...","{'game_id': '401695960', 'language': 'english'...","{'game_id': '401695953', 'language': 'english'...","{'game_id': '401695952', 'language': 'english'...","{'game_id': '401695956', 'language': 'english'...","{'game_id': '401695959', 'language': 'english'...","{'game_id': '401695957', 'language': 'english'...","{'game_id': '401695962', 'language': 'english'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"{'game_id': '401695970', 'language': 'english'...","{'game_id': '401695971', 'language': 'english'...","{'game_id': '401695967', 'language': 'english'...","{'game_id': '401695975', 'language': 'english'...","{'game_id': '401695972', 'language': 'english'...","{'game_id': '401695977', 'language': 'english'...","{'game_id': '401695978', 'language': 'english'...","{'game_id': '401695979', 'language': 'english'...","{'game_id': '401695969', 'language': 'english'...","{'game_id': '401695974', 'language': 'english'...","{'game_id': '401695980', 'language': 'english'...","{'game_id': '401695966', 'language': 'english'...","{'game_id': '401695976', 'language': 'english'...","{'game_id': '401695973', 'language': 'english'...","{'game_id': '401695968', 'language': 'english'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"{'game_id': '401695987', 'language': 'english'...","{'game_id': '401695984', 'language': 'english'...","{'game_id': '401695981', 'language': 'english'...","{'game_id': '401695983', 'language': 'english'...","{'game_id': '401695982', 'language': 'english'...","{'game_id': '401764554', 'language': 'english'...","{'game_id': '401695985', 'language': 'english'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"{'game_id': '401695997', 'language': 'english'...","{'game_id': '401696002', 'language': 'english'...","{'game_id': '401695998', 'language': 'english'...","{'game_id': '401695988', 'language': 'english'...","{'game_id': '401695990', 'language': 'english'...","{'game_id': '401696000', 'language': 'english'...","{'game_id': '401764555', 'language': 'english'...","{'game_id': '401695992', 'language': 'english'...","{'game_id': '401695999', 'language': 'english'...","{'game_id': '401695989', 'language': 'english'...","{'game_id': '401695991', 'language': 'english'...","{'game_id': '401695993', 'language': 'english'...","{'game_id': '401695994', 'language': 'english'...","{'game_id': '401695995', 'language': 'english'...","{'game_id': '401695996', 'language': 'english'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

First cell in the grid: {'game_id': '401695888', 'language': 'english', 'date': '20250608', 'input': "Game between Mariners and Angels.\n\n--- Top 1st ---\nT. ANDERSON PITCHING FOR LAA. (Mariners SEA, Angels LAA)\nCrawford walked. (Mariners 0, Angels 0)\nRodríguez grounded into fielder's choice to pitcher, Crawford out at second. (Mariners 0, Angels 0)\nArozarena doubled to right, Rodríguez scored. (Mariners 1, Angels 0)\nGarver lined out to left. (Mariners 1, Angels 0)\nMoore struck out swinging. (Mariners 1, Angels 0)\n\n--- Bottom 1st ---\nG. KIRBY PITCHING FOR SEA. (Mariners SEA, Angels LAA)\nNeto struck out swinging. (Mariners 1, Angels 0)\nSchanuel flied out to center. (Mariners 1, Angels 0)\nTrout struck out swinging. (Mariners 1, Angels 0)\n\n--- Top 2nd ---\nT. ANDERSON PITCHING FOR LAA. (Mariners SEA, Angels LAA)\nPolanco singled to center. (Mariners 1, Angels 0)\nSolano hit by pitch, Polanco to second. (Mariners 1, Angels 0)\nWilliamson struck out swinging. (Mariners 1, Angels 0)\nYoung flied out to right, Polanco to third. (Mariners 1, Angels 0)\nCrawford flied out to left. (Mariners 1, Angels 0)\n\n--- Bottom 2nd ---\nG. KIRBY PITCHING FOR SEA. (Mariners SEA, Angels LAA)\nWard struck out swinging. (Mariners 1, Angels 0)\nTaylor struck out looking. (Mariners 1, Angels 0)\nO'Hoppe grounded out to shortstop. (Mariners 1, Angels 0)\n\n--- Top 3rd ---\nT. ANDERSON PITCHING FOR LAA. (Mariners SEA, Angels LAA)\nRodríguez safe at first on fielding error by third baseman Rengifo. (Mariners 1, Angels 0)\nArozarena doubled to left, Rodríguez to third. (Mariners 1, Angels 0)\nGarver struck out swinging. (Mariners 1, Angels 0)\nMoore grounded into fielder's choice to third, Rodríguez out at home. (Mariners 1, Angels 0)\nPolanco struck out swinging. (Mariners 1, Angels 0)\n\n--- Bottom 3rd ---\nG. KIRBY PITCHING FOR SEA. (Mariners SEA, Angels LAA)\nRengifo struck out looking. (Mariners 1, Angels 0)\nAdell flied out to right. (Mariners 1, Angels 0)\nKingery struck out swinging. (Mariners 1, Angels 0)\n\n--- Top 4th ---\nT. ANDERSON PITCHING FOR LAA. (Mariners SEA, Angels LAA)\nSolano struck out looking. (Mariners 1, Angels 0)\nWilliamson doubled to center. (Mariners 1, Angels 0)\nYoung flied out to right, Williamson to third. (Mariners 1, Angels 0)\nCrawford lined out to first. (Mariners 1, Angels 0)\n\n--- Bottom 4th ---\nG. KIRBY PITCHING FOR SEA. (Mariners SEA, Angels LAA)\nNeto struck out swinging. (Mariners 1, Angels 0)\nSchanuel struck out looking. (Mariners 1, Angels 0)\nTrout singled to right. (Mariners 1, Angels 0)\nWard homered to left (432 feet), Trout scored. (Mariners 1, Angels 2)\nTaylor struck out looking. (Mariners 1, Angels 2)\n\n--- Top 5th ---\nT. ANDERSON PITCHING FOR LAA. (Mariners SEA, Angels LAA)\nRodríguez flied out to center. (Mariners 1, Angels 2)\nArozarena singled to right. (Mariners 1, Angels 2)\nArozarena stole second. (Mariners 1, Angels 2)\nGarver singled to left, Arozarena to third. (Mariners 1, Angels 2)\nMoore struck out swinging. (Mariners 1, Angels 2)\nPolanco singled to center, Arozarena scored, Garver to third. (Mariners 2, Angels 2)\nSolano singled to center, Garver scored, Polanco to second. (Mariners 3, Angels 2)\nH. STRICKLAND PITCHING FOR LAA. (Mariners SEA, Angels LAA)\nWilliamson reached on infield single to third, Solano to second, Polanco to third. (Mariners 3, Angels 2)\nYoung flied out to second. (Mariners 3, Angels 2)\n\n--- Bottom 5th ---\nG. KIRBY PITCHING FOR SEA. (Mariners SEA, Angels LAA)\nO'Hoppe struck out looking. (Mariners 3, Angels 2)\nRengifo grounded out to second. (Mariners 3, Angels 2)\nAdell struck out swinging. (Mariners 3, Angels 2)\n\n--- Top 6th ---\nH. STRICKLAND PITCHING FOR LAA. (Mariners SEA, Angels LAA)\nCrawford grounded out to shortstop. (Mariners 3, Angels 2)\nRodríguez lined out to left. (Mariners 3, Angels 2)\nArozarena grounded out to shortstop. (Mariners 3, Angels 2)\n\n--- Bottom 6th ---\nG. KIRBY PITCHING FOR SEA. (Mariners SEA, Angels LAA)\nKingery struck out swinging. (Mariners 3, Angels 2)\nNeto flied out to right. (Mariners 3, Angels 2)\nSchanuel fouled out to third. (Mariners 3, Angels 2)\n\n--- Top 7th ---\nH. STRICKLAND PITCHING FOR LAA. (Mariners SEA, Angels LAA)\nGarver struck out swinging. (Mariners 3, Angels 2)\nMastrobuoni hit for Moore. (Mariners 3, Angels 2)\nMastrobuoni singled to left. (Mariners 3, Angels 2)\nPolanco flied out to right. (Mariners 3, Angels 2)\nTellez hit for Solano. (Mariners 3, Angels 2)\nTellez grounded out to second. (Mariners 3, Angels 2)\n\n--- Bottom 7th ---\nG. KIRBY PITCHING FOR SEA. (Mariners SEA, Angels LAA)\nMastrobuoni in right field. (Mariners 3, Angels 2)\nTellez at first base. (Mariners 3, Angels 2)\nTrout struck out looking. (Mariners 3, Angels 2)\nWard struck out looking. (Mariners 3, Angels 2)\nTaylor lined out to shortstop. (Mariners 3, Angels 2)\n\n--- Top 8th ---\nJ. FERMIN PITCHING FOR LAA. (Mariners SEA, Angels LAA)\nWilliamson grounded out to third. (Mariners 3, Angels 2)\nYoung singled to center. (Mariners 3, Angels 2)\nCrawford lined out to shortstop. (Mariners 3, Angels 2)\nRodríguez struck out swinging. (Mariners 3, Angels 2)\n\n--- Bottom 8th ---\nM. BRASH PITCHING FOR SEA. (Mariners SEA, Angels LAA)\nO'Hoppe grounded out to shortstop. (Mariners 3, Angels 2)\nRengifo struck out swinging. (Mariners 3, Angels 2)\nAdell struck out swinging. (Mariners 3, Angels 2)\n\n--- Top 9th ---\nJ. FERMIN PITCHING FOR LAA. (Mariners SEA, Angels LAA)\nArozarena struck out swinging. (Mariners 3, Angels 2)\nGarver struck out swinging. (Mariners 3, Angels 2)\nB. BURKE PITCHING FOR LAA. (Mariners SEA, Angels LAA)\nMastrobuoni struck out swinging. (Mariners 3, Angels 2)\n\n--- Bottom 9th ---\nA. MUNOZ PITCHING FOR SEA. (Mariners SEA, Angels LAA)\nSoler hit for Kingery. (Mariners 3, Angels 2)\nSoler walked. (Mariners 3, Angels 2)\nLugo ran for Soler. (Mariners 3, Angels 2)\nNeto struck out swinging. (Mariners 3, Angels 2)\nSchanuel lined out to right. (Mariners 3, Angels 2)\nTrout struck out swinging. (Mariners 3, Angels 2)", 'ground': '| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n| - | - | - | - | - | - | - | - | - | - |\n| SEA | 1 | 0 | 0 | 0 | 2 | 0 | 0 | 0 | 0 | \n| LAA | 0 | 0 | 0 | 2 | 0 | 0 | 0 | 0 | 0 |'}
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan
Error evaluating literal string: malformed node or string: nan

,game_id,language,date,input,ground
0,401695888,english,20250608,Game between Mariners and Angels.\n\n--- Top 1...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
1,401695875,english,20250608,Game between Red Sox and Yankees.\n\n--- Top 1...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
2,401695885,english,20250608,Game between Mets and Rockies.\n\n--- Top 1st ...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
3,401695884,english,20250608,Game between Blue Jays and Twins.\n\n--- Top 1...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
4,401695879,english,20250608,Game between Phillies and Pirates.\n\n--- Top ...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...

In [7]:
# --- 5. Split the dataframe into multiple DataFrames based on the 'language' column ---
def split_dataframe_by_language(df):
    """
    Splits the DataFrame into multiple DataFrames based on the 'language' column.

    Args:
        df (pd.DataFrame): The DataFrame to split.

    Returns:
        dict: A dictionary where keys are languages and values are DataFrames.
    """
    language_dfs = {}
    for language in df['language'].unique():
        language_dfs[language] = df[df['language'] == language].reset_index(drop=True)
    return language_dfs

In [8]:
split_dfs = split_dataframe_by_language(parsed_df)

In [9]:
# --- 6. print head of each language's datframe to prime for merging ---
for lang, language_df in split_dfs.items():
    print(f"\n--- {lang.capitalize()} DataFrame Preview ---")
    display(language_df.head())

--- English DataFrame Preview ---

,game_id,language,date,input,ground
0,401695888,english,20250608,Game between Mariners and Angels.\n\n--- Top 1...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
1,401695875,english,20250608,Game between Red Sox and Yankees.\n\n--- Top 1...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
2,401695885,english,20250608,Game between Mets and Rockies.\n\n--- Top 1st ...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
3,401695884,english,20250608,Game between Blue Jays and Twins.\n\n--- Top 1...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
4,401695879,english,20250608,Game between Phillies and Pirates.\n\n--- Top ...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...

--- Spanish DataFrame Preview ---

,game_id,language,date,input,ground
0,401695888,spanish,20250608,Game between and .\n\n--- ---\n\n--- ---\n\...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
1,401695875,spanish,20250608,Game between and .\n\n--- ---\n\n--- ---\n\...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
2,401695885,spanish,20250608,Game between and .\n\n--- ---\n\n--- ---\n\...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
3,401695884,spanish,20250608,Game between and .\n\n--- ---\n\n--- ---\n\...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
4,401695879,spanish,20250608,Game between and .\n\n--- ---\n\n--- ---\n\...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...

--- Dutch DataFrame Preview ---

,game_id,language,date,input,ground
0,401695885,dutch,20250608,Game between Mets and Rockies.\n\n--- Top 1ste...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
1,401695884,dutch,20250608,Game between Blue Jays and Twins.\n\n--- Top 1...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
2,401695870,dutch,20250608,Game between Mets and Rockies.\n\n--- Top 1ste...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
3,401695882,dutch,20250608,Game between Dodgers and Cardinals.\n\n--- Top...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
4,401695883,dutch,20250608,Game between Padres and Brewers.\n\n--- Top 1s...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...

In [10]:
# --- 7. Modify the 'input' column to include the 'language' key ---
# a. Extract each language's DataFrame
for lang, language_df in split_dfs.items():
    # b. Add the 'language' key to the 'input' column
    language_df[f'{lang} input'] = language_df['input']
    # c. Update the DataFrame in the dictionary
    split_dfs[lang] = language_df

In [11]:
# --- 8. Extract the three separate dataframes ---
spanish_df = split_dfs.get('spanish', pd.DataFrame())
english_df = split_dfs.get('english', pd.DataFrame())
dutch_df = split_dfs.get('dutch', pd.DataFrame())

In [12]:
# --- 9. Merge the three DataFrames into one, by game id ---
display(spanish_df.head())
display(english_df.head())
display(dutch_df.head())
# Drop the original 'input' column
spanish_df = spanish_df.drop(columns=['input'], errors='ignore')
english_df = english_df.drop(columns=['input'], errors='ignore')
dutch_df = dutch_df.drop(columns=['input'], errors='ignore')

,game_id,language,date,input,ground,spanish input
0,401695888,spanish,20250608,Game between and .\n\n--- ---\n\n--- ---\n\...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between and .\n\n--- ---\n\n--- ---\n\...
1,401695875,spanish,20250608,Game between and .\n\n--- ---\n\n--- ---\n\...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between and .\n\n--- ---\n\n--- ---\n\...
2,401695885,spanish,20250608,Game between and .\n\n--- ---\n\n--- ---\n\...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between and .\n\n--- ---\n\n--- ---\n\...
3,401695884,spanish,20250608,Game between and .\n\n--- ---\n\n--- ---\n\...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between and .\n\n--- ---\n\n--- ---\n\...
4,401695879,spanish,20250608,Game between and .\n\n--- ---\n\n--- ---\n\...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between and .\n\n--- ---\n\n--- ---\n\...

,game_id,language,date,input,ground,english input
0,401695888,english,20250608,Game between Mariners and Angels.\n\n--- Top 1...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Mariners and Angels.\n\n--- Top 1...
1,401695875,english,20250608,Game between Red Sox and Yankees.\n\n--- Top 1...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Red Sox and Yankees.\n\n--- Top 1...
2,401695885,english,20250608,Game between Mets and Rockies.\n\n--- Top 1st ...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Mets and Rockies.\n\n--- Top 1st ...
3,401695884,english,20250608,Game between Blue Jays and Twins.\n\n--- Top 1...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Blue Jays and Twins.\n\n--- Top 1...
4,401695879,english,20250608,Game between Phillies and Pirates.\n\n--- Top ...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Phillies and Pirates.\n\n--- Top ...

,game_id,language,date,input,ground,dutch input
0,401695885,dutch,20250608,Game between Mets and Rockies.\n\n--- Top 1ste...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Mets and Rockies.\n\n--- Top 1ste...
1,401695884,dutch,20250608,Game between Blue Jays and Twins.\n\n--- Top 1...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Blue Jays and Twins.\n\n--- Top 1...
2,401695870,dutch,20250608,Game between Mets and Rockies.\n\n--- Top 1ste...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Mets and Rockies.\n\n--- Top 1ste...
3,401695882,dutch,20250608,Game between Dodgers and Cardinals.\n\n--- Top...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Dodgers and Cardinals.\n\n--- Top...
4,401695883,dutch,20250608,Game between Padres and Brewers.\n\n--- Top 1s...,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Padres and Brewers.\n\n--- Top 1s...

In [13]:
# Merge the DataFrames on 'game_id'
merged_df = pd.merge(english_df, spanish_df, on='game_id', suffixes=('_english', '_spanish'), how='outer')
display(merged_df.head())
# drop the columns with the _spanish suffix
merged_df = merged_df.drop(columns=[col for col in merged_df.columns if col.endswith('_spanish')], errors='ignore')
# drop the language column
merged_df = merged_df.drop(columns=['language_english'], errors='ignore')
merged_df['date'] = merged_df['date_english']
merged_df['Line Score'] = merged_df['ground_english']
# drop the columns with the _english suffix
merged_df = merged_df.drop(columns=[col for col in merged_df.columns if col.endswith('_english')], errors='ignore')
display(merged_df.head())

,game_id,language_english,date_english,ground_english,english input,language_spanish,date_spanish,ground_spanish,spanish input
0,401695874,english,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Diamondbacks and Reds.\n\n--- Top...,spanish,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between and .\n\n--- ---\n\n--- ---\n\...
1,401695875,english,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Red Sox and Yankees.\n\n--- Top 1...,spanish,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between and .\n\n--- ---\n\n--- ---\n\...
2,401695876,english,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Cubs and Tigers.\n\n--- Top 1st -...,spanish,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between and .\n\n--- ---\n\n--- ---\n\...
3,401695877,english,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Astros and Guardians.\n\n--- Top ...,spanish,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between and .\n\n--- ---\n\n--- ---\n\...
4,401695878,english,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Marlins and Rays.\n\n--- Top 1st ...,spanish,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between and .\n\n--- ---\n\n--- ---\n\...

,game_id,english input,spanish input,date,Line Score
0,401695874,Game between Diamondbacks and Reds.\n\n--- Top...,Game between and .\n\n--- ---\n\n--- ---\n\...,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
1,401695875,Game between Red Sox and Yankees.\n\n--- Top 1...,Game between and .\n\n--- ---\n\n--- ---\n\...,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
2,401695876,Game between Cubs and Tigers.\n\n--- Top 1st -...,Game between and .\n\n--- ---\n\n--- ---\n\...,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
3,401695877,Game between Astros and Guardians.\n\n--- Top ...,Game between and .\n\n--- ---\n\n--- ---\n\...,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...
4,401695878,Game between Marlins and Rays.\n\n--- Top 1st ...,Game between and .\n\n--- ---\n\n--- ---\n\...,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...

In [14]:
# Move the date column to position 1
merged_df = merged_df[['game_id', 'date', 'Line Score'] + [col for col in merged_df.columns if col not in ['game_id', 'date', 'Line Score']]]

In [15]:
display(merged_df.head())

,game_id,date,Line Score,english input,spanish input
0,401695874,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Diamondbacks and Reds.\n\n--- Top...,Game between and .\n\n--- ---\n\n--- ---\n\...
1,401695875,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Red Sox and Yankees.\n\n--- Top 1...,Game between and .\n\n--- ---\n\n--- ---\n\...
2,401695876,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Cubs and Tigers.\n\n--- Top 1st -...,Game between and .\n\n--- ---\n\n--- ---\n\...
3,401695877,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Astros and Guardians.\n\n--- Top ...,Game between and .\n\n--- ---\n\n--- ---\n\...
4,401695878,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Marlins and Rays.\n\n--- Top 1st ...,Game between and .\n\n--- ---\n\n--- ---\n\...

In [16]:
# Merge with the dutch DataFrame
merged_df = pd.merge(merged_df, dutch_df, on='game_id', suffixes=('', '_dutch'), how='outer')

In [17]:
display(merged_df.head())

,game_id,date,Line Score,english input,spanish input,language,date_dutch,ground,dutch input
0,401695860,NaN,NaN,NaN,NaN,dutch,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Red Sox and Yankees.\n\n--- Top 1...
1,401695868,NaN,NaN,NaN,NaN,dutch,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Padres and Brewers.\n\n--- Top 1s...
2,401695870,NaN,NaN,NaN,NaN,dutch,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Mets and Rockies.\n\n--- Top 1ste...
3,401695873,NaN,NaN,NaN,NaN,dutch,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Mariners and Angels.\n\n--- Top 1...
4,401695874,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Diamondbacks and Reds.\n\n--- Top...,Game between and .\n\n--- ---\n\n--- ---\n\...,dutch,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Diamondbacks and Reds.\n\n--- Top...

In [18]:
merged_df.drop(columns=['language', 'date_dutch', 'ground'], inplace=True, errors='ignore')

In [19]:
display(merged_df.head())

,game_id,date,Line Score,english input,spanish input,dutch input
0,401695860,NaN,NaN,NaN,NaN,Game between Red Sox and Yankees.\n\n--- Top 1...
1,401695868,NaN,NaN,NaN,NaN,Game between Padres and Brewers.\n\n--- Top 1s...
2,401695870,NaN,NaN,NaN,NaN,Game between Mets and Rockies.\n\n--- Top 1ste...
3,401695873,NaN,NaN,NaN,NaN,Game between Mariners and Angels.\n\n--- Top 1...
4,401695874,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Diamondbacks and Reds.\n\n--- Top...,Game between and .\n\n--- ---\n\n--- ---\n\...,Game between Diamondbacks and Reds.\n\n--- Top...

In [20]:
merged_df.dropna(inplace=True)

In [21]:
display(merged_df.head())

,game_id,date,Line Score,english input,spanish input,dutch input
4,401695874,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Diamondbacks and Reds.\n\n--- Top...,Game between and .\n\n--- ---\n\n--- ---\n\...,Game between Diamondbacks and Reds.\n\n--- Top...
5,401695875,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Red Sox and Yankees.\n\n--- Top 1...,Game between and .\n\n--- ---\n\n--- ---\n\...,Game between Red Sox and Yankees.\n\n--- Top 1...
6,401695876,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Cubs and Tigers.\n\n--- Top 1st -...,Game between and .\n\n--- ---\n\n--- ---\n\...,Game between Cubs and Tigers.\n\n--- Top 1ste ...
7,401695877,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Astros and Guardians.\n\n--- Top ...,Game between and .\n\n--- ---\n\n--- ---\n\...,Game between Astros and Guardians.\n\n--- Top ...
8,401695878,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Marlins and Rays.\n\n--- Top 1st ...,Game between and .\n\n--- ---\n\n--- ---\n\...,Game between Marlins and Rays.\n\n--- Top 1ste...

# Step 3: Processing the Data to make Temporal, Symbolic and Counterfactual commentary (English Only)

In [22]:
# --- 1. From the Merged Dataframe, Extract the English input --- 
english_input = merged_df['english input'].tolist()

## 1. Temporal Commentary

In [23]:
# --- a. Take the input and parse it by looking for the key 'top' or 'bottom' ---
def parse_innings(input_string):
    """
    Parses the input string to extract innings data, organizing it by inning number.

    Args:
        input_string (str): The input string containing innings data.

    Returns:
        dict: A dictionary where keys are inning numbers (1-9) and values are lists
              containing the "Top" and/or "Bottom" data for that inning.
    """
    innings_data = {str(i): [] for i in range(1, 10)}  # Initialize 9 lists for innings 1-9
    lines = input_string.split('\n\n')

    for line in lines:
        # Remove leading/trailing dashes and spaces, then split by space
        cleaned_line = line.strip(' -').strip()
        parts = cleaned_line.split(' ')

        if len(parts) >= 2: # Ensure there are at least two parts (e.g., "Top" and "1st")
            inning_num_str_raw = parts[1] # "1st", "2nd", etc.

            # Extract just the number from "1st", "2nd", etc.
            inning_num_str = ''.join(filter(str.isdigit, inning_num_str_raw))

            if inning_num_str and inning_num_str in innings_data:
                innings_data[inning_num_str].append(line)

    return innings_data
# --- b. Apply the parsing function to the English input ---
parsed_innings = [parse_innings(input_str) for input_str in english_input]
# --- c. Convert the parsed innings into a DataFrame ---
innings_df = pd.DataFrame(parsed_innings)
# --- d. Display the innings DataFrame ---
# --- e. Add the 'game_id' column to the innings DataFrame ---
innings_df['game_id'] = merged_df['game_id'].values
# --- f. Reorder the columns to have 'game_id' first ---
innings_df = innings_df[['game_id'] + [col for col in innings_df.columns if col != 'game_id']]

In [24]:
# --- h. merge the innings DataFrame with the merged DataFrame ---
merged_df = pd.merge(merged_df, innings_df, on='game_id', how='outer')

In [25]:
display(merged_df.head())

,game_id,date,Line Score,english input,spanish input,dutch input,1,2,3,4,5,6,7,8,9
0,401695874,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Diamondbacks and Reds.\n\n--- Top...,Game between and .\n\n--- ---\n\n--- ---\n\...,Game between Diamondbacks and Reds.\n\n--- Top...,[--- Top 1st ---\nB. SINGER PITCHING FOR CIN. ...,[--- Top 2nd ---\nB. SINGER PITCHING FOR CIN. ...,[--- Top 3rd ---\nB. SINGER PITCHING FOR CIN. ...,[--- Top 4th ---\nB. SINGER PITCHING FOR CIN. ...,[--- Top 5th ---\nB. SINGER PITCHING FOR CIN. ...,[--- Top 6th ---\nS. BARLOW PITCHING FOR CIN. ...,[--- Top 7th ---\nT. ROGERS PITCHING FOR CIN. ...,[--- Top 8th ---\nT. ROGERS PITCHING FOR CIN. ...,[--- Top 9th ---\nT. SANTILLAN PITCHING FOR CI...
1,401695875,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Red Sox and Yankees.\n\n--- Top 1...,Game between and .\n\n--- ---\n\n--- ---\n\...,Game between Red Sox and Yankees.\n\n--- Top 1...,[--- Top 1st ---\nC. RODON PITCHING FOR NYY. (...,[--- Top 2nd ---\nC. RODON PITCHING FOR NYY. (...,[--- Top 3rd ---\nC. RODON PITCHING FOR NYY. (...,[--- Top 4th ---\nC. RODON PITCHING FOR NYY. (...,[--- Top 5th ---\nC. RODON PITCHING FOR NYY. (...,[--- Top 6th ---\nC. RODON PITCHING FOR NYY. (...,[--- Top 7th ---\nJ. LOAISIGA PITCHING FOR NYY...,[--- Top 8th ---\nJ. LOAISIGA PITCHING FOR NYY...,[--- Top 9th ---\nB. HEADRICK PITCHING FOR NYY...
2,401695876,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Cubs and Tigers.\n\n--- Top 1st -...,Game between and .\n\n--- ---\n\n--- ---\n\...,Game between Cubs and Tigers.\n\n--- Top 1ste ...,[--- Top 1st ---\nJ. FLAHERTY PITCHING FOR DET...,[--- Top 2nd ---\nJ. FLAHERTY PITCHING FOR DET...,[--- Top 3rd ---\nJ. FLAHERTY PITCHING FOR DET...,[--- Top 4th ---\nJ. FLAHERTY PITCHING FOR DET...,[--- Top 5th ---\nJ. FLAHERTY PITCHING FOR DET...,[--- Top 6th ---\nJ. FLAHERTY PITCHING FOR DET...,[--- Top 7th ---\nB. HANIFEE PITCHING FOR DET....,[--- Top 8th ---\nT. KAHNLE PITCHING FOR DET. ...,[--- Top 9th ---\nW. VEST PITCHING FOR DET. (C...
3,401695877,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Astros and Guardians.\n\n--- Top ...,Game between and .\n\n--- ---\n\n--- ---\n\...,Game between Astros and Guardians.\n\n--- Top ...,[--- Top 1st ---\nT. BIBEE PITCHING FOR CLE. (...,[--- Top 2nd ---\nT. BIBEE PITCHING FOR CLE. (...,[--- Top 3rd ---\nT. BIBEE PITCHING FOR CLE. (...,[--- Top 4th ---\nT. BIBEE PITCHING FOR CLE. (...,[--- Top 5th ---\nT. BIBEE PITCHING FOR CLE. (...,[--- Top 6th ---\nT. BIBEE PITCHING FOR CLE. (...,[--- Top 7th ---\nT. BIBEE PITCHING FOR CLE. (...,[--- Top 8th ---\nC. SMITH PITCHING FOR CLE. (...,[--- Top 9th ---\nE. CLASE PITCHING FOR CLE. (...
4,401695878,20250608,| Team | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n...,Game between Marlins and Rays.\n\n--- Top 1st ...,Game between and .\n\n--- ---\n\n--- ---\n\...,Game between Marlins and Rays.\n\n--- Top 1ste...,[--- Top 1st ---\nD. RASMUSSEN PITCHING FOR TB...,[--- Top 2nd ---\nD. RASMUSSEN PITCHING FOR TB...,[--- Top 3rd ---\nD. RASMUSSEN PITCHING FOR TB...,[--- Top 4th ---\nD. RASMUSSEN PITCHING FOR TB...,[--- Top 5th ---\nD. RASMUSSEN PITCHING FOR TB...,[--- Top 6th ---\nD. RASMUSSEN PITCHING FOR TB...,[--- Top 7th ---\nK. KELLY PITCHING FOR TB. (M...,[--- Top 8th ---\nE. UCETA PITCHING FOR TB. (M...,[--- Top 9th ---\nE. UCETA PITCHING FOR TB. (M...

## 2. Symbolic Commentary (English Only)

In [26]:
#Printing one commentary to see what we have
print("\n--- Sample Commentary ---")
print(merged_df['english input'].iloc[0])

--- Sample Commentary ---
Game between Diamondbacks and Reds.

--- Top 1st ---
B. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Carroll struck out swinging. (Diamondbacks 0, Reds 0)
Marte walked. (Diamondbacks 0, Reds 0)
Perdomo grounded into double play, second to shortstop to first, Marte out at second. (Diamondbacks 0, Reds 0)

--- Bottom 1st ---
Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
Friedl flied out to center. (Diamondbacks 0, Reds 0)
Lux flied out to center. (Diamondbacks 0, Reds 0)
De La Cruz grounded out to second. (Diamondbacks 0, Reds 0)

--- Top 2nd ---
B. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Naylor lined out to left. (Diamondbacks 0, Reds 0)
Suárez homered to center (395 feet). (Diamondbacks 1, Reds 0)
Gurriel Jr. struck out swinging. (Diamondbacks 1, Reds 0)
Smith grounded out to pitcher. (Diamondbacks 1, Reds 0)

--- Bottom 2nd ---
Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
Encarnacion-Strand walked. (Diamondbacks 1, Reds 0)
Benson flied out to center, Encarnacion-Strand to second. (Diamondbacks 1, Reds 0)
Steer struck out swinging. (Diamondbacks 1, Reds 0)
Trevino walked. (Diamondbacks 1, Reds 0)
Fraley struck out swinging. (Diamondbacks 1, Reds 0)

--- Top 3rd ---
B. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Thomas singled to right. (Diamondbacks 1, Reds 0)
Herrera hit sacrifice bunt to pitcher, Thomas to second. (Diamondbacks 1, Reds 0)
Carroll singled to center, Thomas scored. (Diamondbacks 2, Reds 0)
Marte lined out to center. (Diamondbacks 2, Reds 0)
Perdomo flied out to center. (Diamondbacks 2, Reds 0)

--- Bottom 3rd ---
Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
McLain singled to center. (Diamondbacks 2, Reds 0)
Friedl grounded into double play, second to shortstop to first, McLain out at second. (Diamondbacks 2, Reds 0)
Lux flied out to shortstop. (Diamondbacks 2, Reds 0)

--- Top 4th ---
B. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Naylor grounded out to shortstop. (Diamondbacks 2, Reds 0)
Suárez popped out to second. (Diamondbacks 2, Reds 0)
Gurriel Jr. reached on infield single to pitcher. (Diamondbacks 2, Reds 0)
Smith reached on infield single to second, Gurriel Jr. to second. (Diamondbacks 2, Reds 0)
Thomas flied out to center. (Diamondbacks 2, Reds 0)

--- Bottom 4th ---
Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
De La Cruz lined out to right. (Diamondbacks 2, Reds 0)
Encarnacion-Strand homered to left center (403 feet). (Diamondbacks 2, Reds 1)
Benson grounded out to first. (Diamondbacks 2, Reds 1)
Steer struck out looking. (Diamondbacks 2, Reds 1)

--- Top 5th ---
B. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Herrera struck out looking. (Diamondbacks 2, Reds 1)
Carroll walked. (Diamondbacks 2, Reds 1)
Marte walked, Carroll to second. (Diamondbacks 2, Reds 1)
Perdomo grounded into double play, second to shortstop to first, Marte out at second. (Diamondbacks 2, Reds 1)

--- Bottom 5th ---
Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
Trevino homered to left center (389 feet). (Diamondbacks 2, Reds 2)
Fraley grounded out to shortstop. (Diamondbacks 2, Reds 2)
McLain struck out looking. (Diamondbacks 2, Reds 2)
Friedl flied out to right. (Diamondbacks 2, Reds 2)

--- Top 6th ---
S. BARLOW PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Naylor grounded out to first. (Diamondbacks 2, Reds 2)
Suárez struck out swinging. (Diamondbacks 2, Reds 2)
Gurriel Jr. lined out to center. (Diamondbacks 2, Reds 2)

--- Bottom 6th ---
Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
Lux struck out swinging. (Diamondbacks 2, Reds 2)
De La Cruz walked. (Diamondbacks 2, Reds 2)
Encarnacion-Strand singled to left, De La Cruz to second. (Diamondbacks 2, Reds 2)
De La Cruz picked off and caught stealing third. (Diamondbacks 2, Reds 2)
Benson grounded into fielder's choice to first, Encarnacion-Strand out at second. (Diamondbacks 2, Reds 2)

--- Top 7th ---
T. ROGERS PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Grichuk hit for Smith. (Diamondbacks 2, Reds 2)
Grichuk struck out looking. (Diamondbacks 2, Reds 2)
Thomas grounded out to shortstop. (Diamondbacks 2, Reds 2)
Herrera struck out looking. (Diamondbacks 2, Reds 2)

--- Bottom 7th ---
Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
Grichuk as designated hitter. (Diamondbacks 2, Reds 2)
Steer flied out to right. (Diamondbacks 2, Reds 2)
Trevino flied out to left. (Diamondbacks 2, Reds 2)
Fraley singled to right. (Diamondbacks 2, Reds 2)
McLain homered to left (381 feet), Fraley scored. (Diamondbacks 2, Reds 4)
J. BEEKS PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
Friedl flied out to right. (Diamondbacks 2, Reds 4)

--- Top 8th ---
T. ROGERS PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Carroll popped out to third. (Diamondbacks 2, Reds 4)
Marte struck out swinging. (Diamondbacks 2, Reds 4)
Perdomo flied out to center. (Diamondbacks 2, Reds 4)

--- Bottom 8th ---
K. BACKHUS PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
Lux popped out to shortstop. (Diamondbacks 2, Reds 4)
De La Cruz struck out looking. (Diamondbacks 2, Reds 4)
Encarnacion-Strand grounded out to third. (Diamondbacks 2, Reds 4)

--- Top 9th ---
T. SANTILLAN PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Espinal at third base. (Diamondbacks 2, Reds 4)
Naylor grounded out to first. (Diamondbacks 2, Reds 4)
Suárez struck out swinging. (Diamondbacks 2, Reds 4)
Gurriel Jr. grounded out to third. (Diamondbacks 2, Reds 4)

"Game between Diamondbacks and Reds.\n\n--- Top 1st ---\nB. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)\nCarroll struck out swinging. (Diamondbacks 0, Reds 0)\nMarte walked. (Diamondbacks 0, Reds 0)\nPerdomo grounded into double play, second to shortstop to first, Marte out at second. (Diamondbacks 0, Reds 0)\n\n--- Bottom 1st ---\nZ. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)\nFriedl flied out to center. (Diamondbacks 0, Reds 0)\nLux flied out to center. (Diamondbacks 0, Reds 0)\nDe La Cruz grounded out to second. (Diamondbacks 0, Reds 0)\n\n--- Top 2nd ---\nB. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)\nNaylor lined out to left. (Diamondbacks 0, Reds 0)\nSuárez homered to center (395 feet). (Diamondbacks 1, Reds 0)\nGurriel Jr. struck out swinging. (Diamondbacks 1, Reds 0)\nSmith grounded out to pitcher. (Diamondbacks 1, Reds 0)\n\n--- Bottom 2nd ---\nZ. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)\nEncarnacion-Strand walked. (Diamondbacks 1, Reds 0)\nBenson flied out to center, Encarnacion-Strand to second. (Diamondbacks 1, Reds 0)\nSteer struck out swinging. (Diamondbacks 1, Reds 0)\nTrevino walked. (Diamondbacks 1, Reds 0)\nFraley struck out swinging. (Diamondbacks 1, Reds 0)\n\n--- Top 3rd ---\nB. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)\nThomas singled to right. (Diamondbacks 1, Reds 0)\nHerrera hit sacrifice bunt to pitcher, Thomas to second. (Diamondbacks 1, Reds 0)\nCarroll singled to center, Thomas scored. (Diamondbacks 2, Reds 0)\nMarte lined out to center. (Diamondbacks 2, Reds 0)\nPerdomo flied out to center. (Diamondbacks 2, Reds 0)\n\n--- Bottom 3rd ---\nZ. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)\nMcLain singled to center. (Diamondbacks 2, Reds 0)\nFriedl grounded into double play, second to shortstop to first, McLain out at second. (Diamondbacks 2, Reds 0)\nLux flied out to shortstop. (Diamondbacks 2, Reds 0)\n\n--- Top 4th ---\nB. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)\nNaylor grounded out to shortstop. (Diamondbacks 2, Reds 0)\nSuárez popped out to second. (Diamondbacks 2, Reds 0)\nGurriel Jr. reached on infield single to pitcher. (Diamondbacks 2, Reds 0)\nSmith reached on infield single to second, Gurriel Jr. to second. (Diamondbacks 2, Reds 0)\nThomas flied out to center. (Diamondbacks 2, Reds 0)\n\n--- Bottom 4th ---\nZ. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)\nDe La Cruz lined out to right. (Diamondbacks 2, Reds 0)\nEncarnacion-Strand homered to left center (403 feet). (Diamondbacks 2, Reds 1)\nBenson grounded out to first. (Diamondbacks 2, Reds 1)\nSteer struck out looking. (Diamondbacks 2, Reds 1)\n\n--- Top 5th ---\nB. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)\nHerrera struck out looking. (Diamondbacks 2, Reds 1)\nCarroll walked. (Diamondbacks 2, Reds 1)\nMarte walked, Carroll to second. (Diamondbacks 2, Reds 1)\nPerdomo grounded into double play, second to shortstop to first, Marte out at second. (Diamondbacks 2, Reds 1)\n\n--- Bottom 5th ---\nZ. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)\nTrevino homered to left center (389 feet). (Diamondbacks 2, Reds 2)\nFraley grounded out to shortstop. (Diamondbacks 2, Reds 2)\nMcLain struck out looking. (Diamondbacks 2, Reds 2)\nFriedl flied out to right. (Diamondbacks 2, Reds 2)\n\n--- Top 6th ---\nS. BARLOW PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)\nNaylor grounded out to first. (Diamondbacks 2, Reds 2)\nSuárez struck out swinging. (Diamondbacks 2, Reds 2)\nGurriel Jr. lined out to center. (Diamondbacks 2, Reds 2)\n\n--- Bottom 6th ---\nZ. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)\nLux struck out swinging. (Diamondbacks 2, Reds 2)\nDe La Cruz walked. (Diamondbacks 2, Reds 2)\nEncarnacion-Strand singled to left, De La Cruz to second. (Diamondbacks 2, Reds 2)\nDe La Cruz picked off and caught stealing third. (Diamondbacks 2, Reds 2)\nBenson grounded into fielder's choice to first, Encarnacion-Strand out at second. (Diamondbacks 2, Reds 2)\n\n--- Top 7th ---\nT. ROGERS PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)\nGrichuk hit for Smith. (Diamondbacks 2, Reds 2)\nGrichuk struck out looking. (Diamondbacks 2, Reds 2)\nThomas grounded out to shortstop. (Diamondbacks 2, Reds 2)\nHerrera struck out looking. (Diamondbacks 2, Reds 2)\n\n--- Bottom 7th ---\nZ. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)\nGrichuk as designated hitter. (Diamondbacks 2, Reds 2)\nSteer flied out to right. (Diamondbacks 2, Reds 2)\nTrevino flied out to left. (Diamondbacks 2, Reds 2)\nFraley singled to right. (Diamondbacks 2, Reds 2)\nMcLain homered to left (381 feet), Fraley scored. (Diamondbacks 2, Reds 4)\nJ. BEEKS PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)\nFriedl flied out to right. (Diamondbacks 2, Reds 4)\n\n--- Top 8th ---\nT. ROGERS PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)\nCarroll popped out to third. (Diamondbacks 2, Reds 4)\nMarte struck out swinging. (Diamondbacks 2, Reds 4)\nPerdomo flied out to center. (Diamondbacks 2, Reds 4)\n\n--- Bottom 8th ---\nK. BACKHUS PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)\nLux popped out to shortstop. (Diamondbacks 2, Reds 4)\nDe La Cruz struck out looking. (Diamondbacks 2, Reds 4)\nEncarnacion-Strand grounded out to third. (Diamondbacks 2, Reds 4)\n\n--- Top 9th ---\nT. SANTILLAN PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)\nEspinal at third base. (Diamondbacks 2, Reds 4)\nNaylor grounded out to first. (Diamondbacks 2, Reds 4)\nSuárez struck out swinging. (Diamondbacks 2, Reds 4)\nGurriel Jr. grounded out to third. (Diamondbacks 2, Reds 4)"

In [32]:
import re

def anonymize_baseball_commentary(commentary: str) -> str:
    """
    Anonymizes baseball commentary by replacing player names with Player <number>,
    pitcher names with Pitcher <number>, and specific team references with
    TEAM A or TEAM B. It also formats the output with consistent line breaks.

    Args:
        commentary: The raw baseball commentary string.

    Returns:
        The anonymized and formatted commentary string.
    """

    # Start with the original commentary
    anonymized_commentary = commentary

    # 1. Initial Team Anonymization (done on the initial commentary string)
    # Be specific to avoid replacing parts of player names if they contain "reds" or "diamondbacks"
    anonymized_commentary = re.sub(r'Diamondbacks\s*ARI', 'TEAM A', anonymized_commentary)
    anonymized_commentary = re.sub(r'Diamondbacks', 'TEAM A', anonymized_commentary)
    anonymized_commentary = re.sub(r'Reds\s*CIN', 'TEAM B', anonymized_commentary)
    anonymized_commentary = re.sub(r'Reds', 'TEAM B', anonymized_commentary)
    anonymized_commentary = re.sub(r'\(ARI\)', '(TEAM A)', anonymized_commentary)
    anonymized_commentary = re.sub(r'\(CIN\)', '(TEAM B)', anonymized_commentary)
    anonymized_commentary = re.sub(r'ARI\.', 'TEAM A.', anonymized_commentary) # For "PITCHING FOR ARI."
    anonymized_commentary = re.sub(r'CIN\.', 'TEAM B.', anonymized_commentary) # For "PITCHING FOR CIN."

    # 2. Collect all potential player/pitcher names for consistent replacement
    words_to_ignore = {'struck', 'swinging', 'walked', 'grounded', 'into', 'double', 'play', 'second',
                       'shortstop', 'first', 'out', 'at', 'flied', 'to', 'center', 'right', 'left',
                       'pitcher', 'homered', 'feet', 'lined', 'popped', 'single', 'sacrifice', 'bunt',
                       'scored', 'hit', 'infield', 'reached', 'on', 'picked', 'off', 'caught', 'stealing',
                       'fielder\'s', 'choice', 'third', 'for', 'as', 'designated', 'hitter', 'new', 'player',
                       'base', 'looking', 'walk', 'runner', 'on', 'base', 'Game', 'Top', 'Bottom', 'Jr'}

    anonymization_mapping = {}
    pitcher_counter = 0
    player_counter = 0

    # Define a character class for letters (ASCII and common accented) compatible with re.UNICODE
    LETTER_CHARS_REGEX = r"[A-Za-z\u00C0-\u024F\u1E00-\u1EFF]"

    # Pass 1: Identify Pitchers explicitly
    all_pitcher_matches = re.findall(
        r'\b([A-Z]\.?\s?' + LETTER_CHARS_REGEX + r'+(?:[\s\-][A-Z]' + LETTER_CHARS_REGEX + r'+)*?)\s+PITCHING FOR (?:TEAM A|TEAM B)\.',
        anonymized_commentary, re.UNICODE
    )

    for p_name in sorted(list(set(all_pitcher_matches))):
        pitcher_counter += 1
        anonymization_mapping[p_name] = f"Pitcher {pitcher_counter}"

    # Pass 2: Identify all other names that appear as players
    player_name_pattern = re.compile(
        # Mc/Mac names
        r'\b(?:Mc|Mac)' + LETTER_CHARS_REGEX + r'+\'*(?:-' + LETTER_CHARS_REGEX + r'+\'*)?'
        # OR general names
        r'|[A-Z]' + LETTER_CHARS_REGEX + r'*(?:(?:[\s-][A-Z]' + LETTER_CHARS_REGEX + r'*)*)?'
        # OR Initial. Lastname
        r'|[A-Z]\.\s[A-Z]' + LETTER_CHARS_REGEX + r'*(?:(?:[\s-][A-Z]' + LETTER_CHARS_REGEX + r'*)*)?'
        r'(?:\sJr)?\b',
        re.UNICODE
    )

    for match in player_name_pattern.finditer(anonymized_commentary):
        original_name = match.group(0).strip()
        
        if len(original_name) <= 2 and not re.match(r'^[A-Z]\.$', original_name):
            continue
        if original_name.lower() in (w.lower() for w in words_to_ignore):
            continue
        if re.match(r'^\d+$', original_name):
            continue
        if re.match(r'^[A-Z]$', original_name) and not original_name.endswith('.'):
             continue

        if original_name in anonymization_mapping and anonymization_mapping[original_name].startswith("Pitcher"):
            continue

        if "TEAM A" in original_name or "TEAM B" in original_name:
            continue

        if original_name not in anonymization_mapping:
            player_counter += 1
            anonymization_mapping[original_name] = f"Player {player_counter}"

    sorted_original_names = sorted(anonymization_mapping.keys(), key=len, reverse=True)

    # 3. Perform Anonymization Replacements
    for original_name in sorted_original_names:
        escaped_name = re.escape(original_name)
        anonymized_commentary = re.sub(r'\b' + escaped_name + r'\b', anonymization_mapping[original_name], anonymized_commentary)
    
    # 4. Post-anonymization cleanup and formatting (line breaks)

    # Replace "Jr." with "Jr" for consistency
    anonymized_commentary = re.sub(r'Jr\.', 'Jr', anonymized_commentary)
    
    # Remove any extra spaces that might have resulted from replacements
    anonymized_commentary = re.sub(r'\s{2,}', ' ', anonymized_commentary)

    # Remove any stray dots from initials that might be left if not part of a name capture
    anonymized_commentary = re.sub(r'\b([A-Z])\.\s', r'\1 ', anonymized_commentary)

    # --- Apply desired line breaks ---

    # Add a double newline AFTER the initial "Game between..." line
    anonymized_commentary = re.sub(r'Game between (TEAM A|TEAM B) and (TEAM A|TEAM B)\.', r'Game between \1 and \2.\n\n', anonymized_commentary, 1)

    # Ensure a double newline BEFORE every inning marker (e.g., "--- Top 1st ---")
    # This also adds a single newline AFTER it.
    anonymized_commentary = re.sub(r'(?<!\n)\n?--- (Top|Bottom \d+th) ---', r'\n\n--- \1 ---\n', anonymized_commentary)

    # Add a single newline after each score update (e.g., "(TEAM A 0, TEAM B 0)")
    # This regex looks for a closing parenthesis followed by optional whitespace and then any character
    # that is NOT the start of "---" (to avoid adding a newline right before inning markers, as that's handled above)
    anonymized_commentary = re.sub(r'\)(\s*)(?!---)([A-Za-z0-9])', r')\n\2', anonymized_commentary)

    # Finally, ensure no more than two consecutive newlines anywhere, and strip overall leading/trailing whitespace.
    # This helps in cleaning up any accidental triples or more, while preserving doubles.
    anonymized_commentary = re.sub(r'\n{3,}', r'\n\n', anonymized_commentary).strip()
    
    return anonymized_commentary

# Provided commentary string
commentary = """Game between Diamondbacks and Reds.--- Top 1st ---B. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)Carroll struck out swinging. (Diamondbacks 0, Reds 0)Marte walked. (Diamondbacks 0, Reds 0)Perdomo grounded into double play, second to shortstop to first, Marte out at second. (Diamondbacks 0, Reds 0)--- Bottom 1st ---Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)Friedl flied out to center. (Diamondbacks 0, Reds 0)Lux flied out to center. (Diamondbacks 0, Reds 0)De La Cruz grounded out to second. (Diamondbacks 0, Reds 0)--- Top 2nd ---B. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)Naylor lined out to left. (Diamondbacks 0, Reds 0)Suárez homered to center (395 feet). (Diamondbacks 1, Reds 0)Gurriel Jr. struck out swinging. (Diamondbacks 1, Reds 0)Smith grounded out to pitcher. (Diamondbacks 1, Reds 0)--- Bottom 2nd ---Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)Encarnacion-Strand walked. (Diamondbacks 1, Reds 0)Benson flied out to center, Encarnacion-Strand to second. (Diamondbacks 1, Reds 0)Steer struck out swinging. (Diamondbacks 1, Reds 0)Trevino walked. (Diamondbacks 1, Reds 0)Fraley struck out swinging. (Diamondbacks 1, Reds 0)--- Top 3rd ---B. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)Thomas singled to right. (Diamondbacks 1, Reds 0)Herrera hit sacrifice bunt to pitcher, Thomas to second. (Diamondbacks 1, Reds 0)Carroll singled to center, Thomas scored. (Diamondbacks 2, Reds 0)Marte lined out to center. (Diamondbacks 2, Reds 0)Perdomo flied out to center. (Diamondbacks 2, Reds 0)--- Bottom 3rd ---Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)McLain singled to center. (Diamondbacks 2, Reds 0)Friedl grounded into double play, second to shortstop to first, McLain out at second. (Diamondbacks 2, Reds 0)Lux flied out to shortstop. (Diamondbacks 2, Reds 0)--- Top 4th ---B. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)Naylor grounded out to shortstop. (Diamondbacks 2, Reds 0)Suárez popped out to second. (Diamondbacks 2, Reds 0)Gurriel Jr. reached on infield single to pitcher. (Diamondbacks 2, Reds 0)Smith reached on infield single to second, Gurriel Jr. to second. (Diamondbacks 2, Reds 0)Thomas flied out to center. (Diamondbacks 2, Reds 0)--- Bottom 4th ---Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)De La Cruz lined out to right. (Diamondbacks 2, Reds 0)Encarnacion-Strand homered to left center (403 feet). (Diamondbacks 2, Reds 1)Benson grounded out to first. (Diamondbacks 2, Reds 1)Steer struck out looking. (Diamondbacks 2, Reds 1)--- Top 5th ---B. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)Herrera struck out looking. (Diamondbacks 2, Reds 1)Carroll walked. (Diamondbacks 2, Reds 1)Marte walked, Carroll to second. (Diamondbacks 2, Reds 1)Perdomo grounded into double play, second to shortstop to first, Marte out at second. (Diamondbacks 2, Reds 1)--- Bottom 5th ---Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)Trevino homered to left center (389 feet). (Diamondbacks 2, Reds 2)Fraley grounded out to shortstop. (Diamondbacks 2, Reds 2)McLain struck out looking. (Diamondbacks 2, Reds 2)Friedl flied out to right. (Diamondbacks 2, Reds 2)--- Top 6th ---S. BARLOW PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)Naylor grounded out to first. (Diamondbacks 2, Reds 2)Suárez struck out swinging. (Diamondbacks 2, Reds 2)Gurriel Jr. lined out to center. (Diamondbacks 2, Reds 2)--- Bottom 6th ---Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)Lux struck out swinging. (Diamondbacks 2, Reds 2)De La Cruz walked. (Diamondbacks 2, Reds 2)Encarnacion-Strand singled to left, De La Cruz to second. (Diamondbacks 2, Reds 2)De La Cruz picked off and caught stealing third. (Diamondbacks 2, Reds 2)Benson grounded into fielder's choice to first, Encarnacion-Strand out at second. (Diamondbacks 2, Reds 2)--- Top 7th ---T. ROGERS PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)Grichuk hit for Smith. (Diamondbacks 2, Reds 2)Grichuk struck out looking. (Diamondbacks 2, Reds 2)Thomas grounded out to shortstop. (Diamondbacks 2, Reds 2)Herrera struck out looking. (Diamondbacks 2, Reds 2)--- Bottom 7th ---Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)Grichuk as designated hitter. (Diamondbacks 2, Reds 2)Steer flied out to right. (Diamondbacks 2, Reds 2)Trevino flied out to left. (Diamondbacks 2, Reds 2)Fraley singled to right. (Diamondbacks 2, Reds 2)McLain homered to left (381 feet), Fraley scored. (Diamondbacks 2, Reds 4)J. BEEKS PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)Friedl flied out to right. (Diamondbacks 2, Reds 4)--- Top 8th ---T. ROGERS PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)Carroll popped out to third. (Diamondbacks 2, Reds 4)Marte struck out swinging. (Diamondbacks 2, Reds 4)Perdomo flied out to center. (Diamondbacks 2, Reds 4)--- Bottom 8th ---K. BACKHUS PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)Lux popped out to shortstop. (Diamondbacks 2, Reds 4)De La Cruz struck out looking. (Diamondbacks 2, Reds 4)Encarnacion-Strand grounded out to third. (Diamondbacks 2, Reds 4)--- Top 9th ---T. SANTILLAN PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)Espinal at third base. (Diamondbacks 2, Reds 4)Naylor grounded out to first. (Diamondbacks 2, Reds 4)Suárez struck out swinging. (Diamondbacks 2, Reds 4)Gurriel Jr. grounded out to third. (Diamondbacks 2, Reds 4)"""

# Call the function to get the anonymized and formatted string
anonymized_commentary_output = anonymize_baseball_commentary(commentary)

# Print the resulting string
print("\n--- Original Commentary ---")
print(merged_df['english input'].iloc[0]) # Prints the original commentary for comparison

--- Original Commentary ---
Game between Diamondbacks and Reds.

--- Top 1st ---
B. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Carroll struck out swinging. (Diamondbacks 0, Reds 0)
Marte walked. (Diamondbacks 0, Reds 0)
Perdomo grounded into double play, second to shortstop to first, Marte out at second. (Diamondbacks 0, Reds 0)

--- Bottom 1st ---
Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
Friedl flied out to center. (Diamondbacks 0, Reds 0)
Lux flied out to center. (Diamondbacks 0, Reds 0)
De La Cruz grounded out to second. (Diamondbacks 0, Reds 0)

--- Top 2nd ---
B. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Naylor lined out to left. (Diamondbacks 0, Reds 0)
Suárez homered to center (395 feet). (Diamondbacks 1, Reds 0)
Gurriel Jr. struck out swinging. (Diamondbacks 1, Reds 0)
Smith grounded out to pitcher. (Diamondbacks 1, Reds 0)

--- Bottom 2nd ---
Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
Encarnacion-Strand walked. (Diamondbacks 1, Reds 0)
Benson flied out to center, Encarnacion-Strand to second. (Diamondbacks 1, Reds 0)
Steer struck out swinging. (Diamondbacks 1, Reds 0)
Trevino walked. (Diamondbacks 1, Reds 0)
Fraley struck out swinging. (Diamondbacks 1, Reds 0)

--- Top 3rd ---
B. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Thomas singled to right. (Diamondbacks 1, Reds 0)
Herrera hit sacrifice bunt to pitcher, Thomas to second. (Diamondbacks 1, Reds 0)
Carroll singled to center, Thomas scored. (Diamondbacks 2, Reds 0)
Marte lined out to center. (Diamondbacks 2, Reds 0)
Perdomo flied out to center. (Diamondbacks 2, Reds 0)

--- Bottom 3rd ---
Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
McLain singled to center. (Diamondbacks 2, Reds 0)
Friedl grounded into double play, second to shortstop to first, McLain out at second. (Diamondbacks 2, Reds 0)
Lux flied out to shortstop. (Diamondbacks 2, Reds 0)

--- Top 4th ---
B. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Naylor grounded out to shortstop. (Diamondbacks 2, Reds 0)
Suárez popped out to second. (Diamondbacks 2, Reds 0)
Gurriel Jr. reached on infield single to pitcher. (Diamondbacks 2, Reds 0)
Smith reached on infield single to second, Gurriel Jr. to second. (Diamondbacks 2, Reds 0)
Thomas flied out to center. (Diamondbacks 2, Reds 0)

--- Bottom 4th ---
Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
De La Cruz lined out to right. (Diamondbacks 2, Reds 0)
Encarnacion-Strand homered to left center (403 feet). (Diamondbacks 2, Reds 1)
Benson grounded out to first. (Diamondbacks 2, Reds 1)
Steer struck out looking. (Diamondbacks 2, Reds 1)

--- Top 5th ---
B. SINGER PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Herrera struck out looking. (Diamondbacks 2, Reds 1)
Carroll walked. (Diamondbacks 2, Reds 1)
Marte walked, Carroll to second. (Diamondbacks 2, Reds 1)
Perdomo grounded into double play, second to shortstop to first, Marte out at second. (Diamondbacks 2, Reds 1)

--- Bottom 5th ---
Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
Trevino homered to left center (389 feet). (Diamondbacks 2, Reds 2)
Fraley grounded out to shortstop. (Diamondbacks 2, Reds 2)
McLain struck out looking. (Diamondbacks 2, Reds 2)
Friedl flied out to right. (Diamondbacks 2, Reds 2)

--- Top 6th ---
S. BARLOW PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Naylor grounded out to first. (Diamondbacks 2, Reds 2)
Suárez struck out swinging. (Diamondbacks 2, Reds 2)
Gurriel Jr. lined out to center. (Diamondbacks 2, Reds 2)

--- Bottom 6th ---
Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
Lux struck out swinging. (Diamondbacks 2, Reds 2)
De La Cruz walked. (Diamondbacks 2, Reds 2)
Encarnacion-Strand singled to left, De La Cruz to second. (Diamondbacks 2, Reds 2)
De La Cruz picked off and caught stealing third. (Diamondbacks 2, Reds 2)
Benson grounded into fielder's choice to first, Encarnacion-Strand out at second. (Diamondbacks 2, Reds 2)

--- Top 7th ---
T. ROGERS PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Grichuk hit for Smith. (Diamondbacks 2, Reds 2)
Grichuk struck out looking. (Diamondbacks 2, Reds 2)
Thomas grounded out to shortstop. (Diamondbacks 2, Reds 2)
Herrera struck out looking. (Diamondbacks 2, Reds 2)

--- Bottom 7th ---
Z. GALLEN PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
Grichuk as designated hitter. (Diamondbacks 2, Reds 2)
Steer flied out to right. (Diamondbacks 2, Reds 2)
Trevino flied out to left. (Diamondbacks 2, Reds 2)
Fraley singled to right. (Diamondbacks 2, Reds 2)
McLain homered to left (381 feet), Fraley scored. (Diamondbacks 2, Reds 4)
J. BEEKS PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
Friedl flied out to right. (Diamondbacks 2, Reds 4)

--- Top 8th ---
T. ROGERS PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Carroll popped out to third. (Diamondbacks 2, Reds 4)
Marte struck out swinging. (Diamondbacks 2, Reds 4)
Perdomo flied out to center. (Diamondbacks 2, Reds 4)

--- Bottom 8th ---
K. BACKHUS PITCHING FOR ARI. (Diamondbacks ARI, Reds CIN)
Lux popped out to shortstop. (Diamondbacks 2, Reds 4)
De La Cruz struck out looking. (Diamondbacks 2, Reds 4)
Encarnacion-Strand grounded out to third. (Diamondbacks 2, Reds 4)

--- Top 9th ---
T. SANTILLAN PITCHING FOR CIN. (Diamondbacks ARI, Reds CIN)
Espinal at third base. (Diamondbacks 2, Reds 4)
Naylor grounded out to first. (Diamondbacks 2, Reds 4)
Suárez struck out swinging. (Diamondbacks 2, Reds 4)
Gurriel Jr. grounded out to third. (Diamondbacks 2, Reds 4)

In [33]:
print("\n--- Anonymized Commentary Output ---")
print(anonymized_commentary_output)

--- Anonymized Commentary Output ---
Game between TEAM A and TEAM B.

--- Top 1st ---Pitcher 1 PITCHING FOR TEAM B (TEAM A, TEAM B)
Player 1 struck out swinging. (TEAM A 0, TEAM B 0)
Player 2 walked. (TEAM A 0, TEAM B 0)
Player 3 grounded into double play, second to shortstop to first, Player 2 out at second. (TEAM A 0, TEAM B 0)--- Bottom 1st ---Pitcher 7 PITCHING FOR TEAM A (TEAM A, TEAM B)
Player 4 flied out to center. (TEAM A 0, TEAM B 0)
Player 5 flied out to center. (TEAM A 0, TEAM B 0)
Player 6 grounded out to second. (TEAM A 0, TEAM B 0)--- Top 2nd ---Pitcher 1 PITCHING FOR TEAM B (TEAM A, TEAM B)
Player 7 lined out to left. (TEAM A 0, TEAM B 0)
Player 8 homered to center (395 feet). (TEAM A 1, TEAM B 0)
Player 9. struck out swinging. (TEAM A 1, TEAM B 0)
Player 10 grounded out to pitcher. (TEAM A 1, TEAM B 0)--- Bottom 2nd ---Pitcher 7 PITCHING FOR TEAM A (TEAM A, TEAM B)
Player 11 walked. (TEAM A 1, TEAM B 0)
Player 12 flied out to center, Player 11 to second. (TEAM A 1, TEAM B 0)
Player 13 struck out swinging. (TEAM A 1, TEAM B 0)
Player 14 walked. (TEAM A 1, TEAM B 0)
Player 15 struck out swinging. (TEAM A 1, TEAM B 0)--- Top 3rd ---Pitcher 1 PITCHING FOR TEAM B (TEAM A, TEAM B)
Player 16 singled to right. (TEAM A 1, TEAM B 0)
Player 17 hit sacrifice bunt to pitcher, Player 16 to second. (TEAM A 1, TEAM B 0)
Player 1 singled to center, Player 16 scored. (TEAM A 2, TEAM B 0)
Player 2 lined out to center. (TEAM A 2, TEAM B 0)
Player 3 flied out to center. (TEAM A 2, TEAM B 0)--- Bottom 3rd ---Pitcher 7 PITCHING FOR TEAM A (TEAM A, TEAM B)
Player 18 singled to center. (TEAM A 2, TEAM B 0)
Player 4 grounded into double play, second to shortstop to first, Player 18 out at second. (TEAM A 2, TEAM B 0)
Player 5 flied out to shortstop. (TEAM A 2, TEAM B 0)--- Top 4th ---Pitcher 1 PITCHING FOR TEAM B (TEAM A, TEAM B)
Player 7 grounded out to shortstop. (TEAM A 2, TEAM B 0)
Player 8 popped out to second. (TEAM A 2, TEAM B 0)
Player 9. reached on infield single to pitcher. (TEAM A 2, TEAM B 0)
Player 10 reached on infield single to second, Player 9. to second. (TEAM A 2, TEAM B 0)
Player 16 flied out to center. (TEAM A 2, TEAM B 0)

--- Bottom 4th ---
Pitcher 7 PITCHING FOR TEAM A (TEAM A, TEAM B)
Player 6 lined out to right. (TEAM A 2, TEAM B 0)
Player 11 homered to left center (403 feet). (TEAM A 2, TEAM B 1)
Player 12 grounded out to first. (TEAM A 2, TEAM B 1)
Player 13 struck out looking. (TEAM A 2, TEAM B 1)--- Top 5th ---Pitcher 1 PITCHING FOR TEAM B (TEAM A, TEAM B)
Player 17 struck out looking. (TEAM A 2, TEAM B 1)
Player 1 walked. (TEAM A 2, TEAM B 1)
Player 2 walked, Player 1 to second. (TEAM A 2, TEAM B 1)
Player 3 grounded into double play, second to shortstop to first, Player 2 out at second. (TEAM A 2, TEAM B 1)

--- Bottom 5th ---
Pitcher 7 PITCHING FOR TEAM A (TEAM A, TEAM B)
Player 14 homered to left center (389 feet). (TEAM A 2, TEAM B 2)
Player 15 grounded out to shortstop. (TEAM A 2, TEAM B 2)
Player 18 struck out looking. (TEAM A 2, TEAM B 2)
Player 4 flied out to right. (TEAM A 2, TEAM B 2)--- Top 6th ---Pitcher 4 PITCHING FOR TEAM B (TEAM A, TEAM B)
Player 7 grounded out to first. (TEAM A 2, TEAM B 2)
Player 8 struck out swinging. (TEAM A 2, TEAM B 2)
Player 9. lined out to center. (TEAM A 2, TEAM B 2)

--- Bottom 6th ---
Pitcher 7 PITCHING FOR TEAM A (TEAM A, TEAM B)
Player 5 struck out swinging. (TEAM A 2, TEAM B 2)
Player 6 walked. (TEAM A 2, TEAM B 2)
Player 11 singled to left, Player 6 to second. (TEAM A 2, TEAM B 2)
Player 6 picked off and caught stealing third. (TEAM A 2, TEAM B 2)
Player 12 grounded into fielder's choice to first, Player 11 out at second. (TEAM A 2, TEAM B 2)--- Top 7th ---Pitcher 5 PITCHING FOR TEAM B (TEAM A, TEAM B)
Player 19 hit for Player 10. (TEAM A 2, TEAM B 2)
Player 19 struck out looking. (TEAM A 2, TEAM B 2)
Player 16 grounded out to shortstop. (TEAM A 2, TEAM B 2)
Player 17 struck out looking. (TEAM A 2, TEAM B 2)

--- Bottom 7th ---
Pitcher 7 PITCHING FOR TEAM A (TEAM A, TEAM B)
Player 19 as designated hitter. (TEAM A 2, TEAM B 2)
Player 13 flied out to right. (TEAM A 2, TEAM B 2)
Player 14 flied out to left. (TEAM A 2, TEAM B 2)
Player 15 singled to right. (TEAM A 2, TEAM B 2)
Player 18 homered to left (381 feet), Player 15 scored. (TEAM A 2, TEAM B 4)
Pitcher 2 PITCHING FOR TEAM A (TEAM A, TEAM B)
Player 4 flied out to right. (TEAM A 2, TEAM B 4)--- Top 8th ---Pitcher 5 PITCHING FOR TEAM B (TEAM A, TEAM B)
Player 1 popped out to third. (TEAM A 2, TEAM B 4)
Player 2 struck out swinging. (TEAM A 2, TEAM B 4)
Player 3 flied out to center. (TEAM A 2, TEAM B 4)

--- Bottom 8th ---
Pitcher 3 PITCHING FOR TEAM A (TEAM A, TEAM B)
Player 5 popped out to shortstop. (TEAM A 2, TEAM B 4)
Player 6 struck out looking. (TEAM A 2, TEAM B 4)
Player 11 grounded out to third. (TEAM A 2, TEAM B 4)--- Top 9th ---Pitcher 6 PITCHING FOR TEAM B (TEAM A, TEAM B)
Player 20 at third base. (TEAM A 2, TEAM B 4)
Player 7 grounded out to first. (TEAM A 2, TEAM B 4)
Player 8 struck out swinging. (TEAM A 2, TEAM B 4)
Player 9. grounded out to third. (TEAM A 2, TEAM B 4)

## 3. Counterfactual Commentary (English Only)