In [1]:
import pandas as pd
import os
import csv
import json # Import json for loading dataset.json

# --- Configuration ---
# --- Pandas Display Options (Add these lines) ---
pd.set_option('display.max_columns', None)  # Display all columns
pd.set_option('display.width', 5000)      # Set a wider display width to prevent truncation
pd.set_option('display.max_rows', None)   # Display all rows (if matching_matches has many rows)
# pd.set_option('display.colheader_justify', 'left') # Optional: Adjust column header alignment

# Set the directory for your main Premier League data
DATA_DIR = './LiveSum_++/english-premier-league/'
# Set the directory for your individual match stat files (e.g., sample_1_table.csv)
SAMPLE_DATA_DIR = './LiveSum_++/training_data/'
# Set the directory for your dataset.json file
DATASET_JSON_PATH = './LiveSum_++/dataset.json' # Define path for dataset.json

# List of CSV files to process for the main historical data
CSV_FILES = [f'{year}-{str(int(year) + 1)[-2:]}.csv'
             for year in range(2013, 2024)] # Generates '2013-14.csv', '2014-15.csv', etc. up to '2021-22.csv'

# --- Dynamic TARGET_STATS Population Function ---
def populate_target_stats_from_csv(file_number, data_directory):
    """
    Populates the TARGET_STATS dictionary dynamically from a single CSV file
    with 'Away Team' and 'Home Team' data on separate rows.

    Args:
        file_number (int): The number of the CSV file to read (e.g., 1 for sample_1_table.csv).
        data_directory (str): The directory where the CSV files are located (e.g., SAMPLE_DATA_DIR).

    Returns:
        tuple: A tuple containing the dynamically populated TARGET_STATS dictionary and
               a list of column names extracted from the sample CSV's header (excluding 'Team').
               Returns (None, None) if the file/data is not found or an error occurs.
    """
    file_name = f"sample_{file_number}_table.csv"
    file_path = os.path.join(data_directory, file_name)

    dynamic_target_stats = {}
    sample_columns = []

    try:
        with open(file_path, mode='r') as csvfile:
            reader = csv.reader(csvfile)

            # Read the header row and strip whitespace
            header = [h.strip() for h in next(reader)]

            # Find the indices of the columns we need
            column_indices = {}
            for i, col_name in enumerate(header):
                column_indices[col_name] = i
                if col_name != 'Team': # Collect column names from sample, excluding 'Team'
                    sample_columns.append(col_name)

            if 'Team' not in column_indices:
                return None, None

            away_data = None
            home_data = None

            # Read the next two rows (Away Team and Home Team)
            try:
                row1 = [d.strip() for d in next(reader)]
                row2 = [d.strip() for d in next(reader)]
            except StopIteration:
                return None, None

            # Determine which row is Away and which is Home
            team_col_idx = column_indices['Team']
            if row1[team_col_idx].lower() == 'away team' and row2[team_col_idx].lower() == 'home team':
                away_data = row1
                home_data = row2
            elif row1[team_col_idx].lower() == 'home team' and row2[team_col_idx].lower() == 'away team':
                away_data = row2
                home_data = row1
            else:
                return None, None

            # Helper to safely get integer value
            def get_stat_value(data_row, stat_name_in_csv):
                if stat_name_in_csv in column_indices:
                    try:
                        return int(data_row[column_indices[stat_name_in_csv]])
                    except ValueError:
                        return None
                return None

            # Populate dynamic_target_stats for Away Team
            goals_away = get_stat_value(away_data, 'Goals')
            if goals_away is not None: dynamic_target_stats['FTAG'] = {'operator': '==', 'value': goals_away}
            shots_away = get_stat_value(away_data, 'Shots')
            if shots_away is not None: dynamic_target_stats['AS'] = {'operator': '==', 'value': shots_away}
            fouls_away = get_stat_value(away_data, 'Fouls')
            if fouls_away is not None: dynamic_target_stats['AF'] = {'operator': '==', 'value': fouls_away}
            yellow_away = get_stat_value(away_data, 'Yellow Cards')
            if yellow_away is not None: dynamic_target_stats['AY'] = {'operator': '==', 'value': yellow_away}
            red_away = get_stat_value(away_data, 'Red Cards')
            if red_away is not None: dynamic_target_stats['AR'] = {'operator': '==', 'value': red_away}
            corners_away = get_stat_value(away_data, 'Corner Kicks')
            if corners_away is not None: dynamic_target_stats['AC'] = {'operator': '==', 'value': corners_away}

            # Populate dynamic_target_stats for Home Team
            goals_home = get_stat_value(home_data, 'Goals')
            if goals_home is not None: dynamic_target_stats['FTHG'] = {'operator': '==', 'value': goals_home}
            shots_home = get_stat_value(home_data, 'Shots')
            if shots_home is not None: dynamic_target_stats['HS'] = {'operator': '==', 'value': shots_home}
            fouls_home = get_stat_value(home_data, 'Fouls')
            if fouls_home is not None: dynamic_target_stats['HF'] = {'operator': '==', 'value': fouls_home}
            yellow_home = get_stat_value(home_data, 'Yellow Cards')
            if yellow_home is not None: dynamic_target_stats['HY'] = {'operator': '==', 'value': yellow_home}
            red_home = get_stat_value(home_data, 'Red Cards')
            if red_home is not None: dynamic_target_stats['HR'] = {'operator': '==', 'value': red_home}
            corners_home = get_stat_value(home_data, 'Corner Kicks')
            if corners_home is not None: dynamic_target_stats['HC'] = {'operator': '==', 'value': corners_home}

            return dynamic_target_stats, sample_columns

    except FileNotFoundError:
        print(f"Error: Sample file not found at {file_path}")
        return None, None
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return None, None

## Core Data Loading and Filtering Functions
def load_and_combine_data(data_directory, csv_files, columns_to_keep=None):
    """
    Loads multiple CSV files from a directory into a single Pandas DataFrame.
    Assumes CSVs contain Premier League match data.
    Optionally drops columns not in `columns_to_keep`.
    """
    all_data = []
    for filename in csv_files:
        filepath = os.path.join(data_directory, filename)
        if os.path.exists(filepath):
            try:
                df = pd.read_csv(filepath, encoding='latin1')
                df['Season'] = filename.split('.')[0] # Add a 'Season' column

                if columns_to_keep:
                    cols_to_drop = [col for col in df.columns if col not in columns_to_keep and col != 'Season']
                    if cols_to_drop:
                        df = df.drop(columns=cols_to_drop)

                all_data.append(df)
            except Exception as e:
                print(f"Error loading {filename}: {e}")
        else:
            print(f"File not found: {filename}")

    if all_data:
        combined_df = pd.concat(all_data, ignore_index=True)
        return combined_df
    else:
        print("No data loaded. Please check your DATA_DIR and CSV_FILES list.")
        return pd.DataFrame()

def find_matches_by_stats(dataframe, target_stats):
    """
    Filters a DataFrame to find matches that meet the specified statistical criteria.
    """
    if dataframe.empty:
        return pd.DataFrame()

    condition = pd.Series(True, index=dataframe.index)

    for col, criteria in target_stats.items():
        if col in dataframe.columns:
            operator = criteria['operator']
            value = criteria['value']

            # Ensure the column's data type is compatible for comparison
            # Attempt to convert to numeric if not already, ignoring errors
            if pd.api.types.is_numeric_dtype(dataframe[col]):
                pass # Already numeric, no conversion needed
            else:
                try:
                    dataframe[col] = pd.to_numeric(dataframe[col], errors='coerce')
                except TypeError:
                    print(f"Warning: Cannot convert column '{col}' to numeric for comparison.")
                    continue # Skip this column if conversion fails

            # Apply condition only if value is not None (from get_stat_value) and column is not NaN
            if value is not None:
                if operator == '>':
                    condition &= (dataframe[col] > value)
                elif operator == '<':
                    condition &= (dataframe[col] < value)
                elif operator == '==':
                    condition &= (dataframe[col] == value)
                elif operator == '>=':
                    condition &= (dataframe[col] >= value)
                elif operator == '<=':
                    condition &= (dataframe[col] <= value)
                elif operator == '!=':
                    condition &= (dataframe[col] != value)
                else:
                    pass
        else:
            pass

    return dataframe[condition]

# --- Main Execution Logic for Automation ---
if __name__ == "__main__":
    print(f"Using main data directory: {DATA_DIR}")
    print(f"Using sample data directory: {SAMPLE_DATA_DIR}")
    print(f"CSV files to process (main data): {CSV_FILES}")

    # Create a set of columns expected in the main dataframe, derived from the sample's relevant columns
    # and common match identifiers.
    main_df_relevant_columns = set([
        'HomeTeam', 'AwayTeam', 'FTR', 'Div', 'Date', 'Referee', # Common match identifiers
        'FTHG', 'FTAG', 'HS', 'AS', 'HF', 'AF', 'HY', 'AY', 'HR', 'AR', 'HC', 'AC', 'HTHG', 'HTAG', 'HTR',
        # Include all relevant stat columns for display
        'Shots', 'ShotsOnTarget', 'Fouls', 'Corners', 'YellowCards', 'RedCards',
        'HST', 'AST', 'HC', 'AC', 'HF', 'AF', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A' # Example betting odds
    ])

    print("\nLoading and combining main Premier League data...")
    combined_football_data = load_and_combine_data(DATA_DIR, CSV_FILES, columns_to_keep=main_df_relevant_columns)

    if combined_football_data.empty:
        print("Failed to load any main Premier League data. Exiting.")
    else:
        print(f"\nSuccessfully loaded {len(combined_football_data)} rows of historical Premier League data.")
        print("First 5 rows of combined main data:")
        try:
            from IPython.display import display
            display(combined_football_data.head())
        except ImportError:
            print(combined_football_data.head().to_string())

        # List all sample files
        sample_files = [f for f in os.listdir(SAMPLE_DATA_DIR) if f.startswith('sample_') and f.endswith('_table.csv')]
        sample_numbers = []
        for f in sample_files:
            try:
                num_part = f.replace('sample_', '').replace('_table.csv', '')
                sample_numbers.append(int(num_part))
            except ValueError:
                continue # Skip files that don't match the expected numeric pattern
        sample_numbers.sort()

        print("\n--- Matching Sample Files to Historical Data ---")
        results = []
        total_samples_processed = 0
        total_matches_found = 0
        total_no_conclusive_result = 0

        # Define columns to display for the matched historical data
        display_cols_for_match = [
            'Season', 'Date', 'HomeTeam', 'AwayTeam', 'FTR', 'FTHG', 'FTAG',
            'HS', 'AS', 'HST', 'AST', 'HC', 'AC', 'HF', 'AF', 'HY', 'AY', 'HR', 'AR'
        ]

        for sample_num in sample_numbers:
            total_samples_processed += 1
            dynamic_target_stats, _ = populate_target_stats_from_csv(sample_num, SAMPLE_DATA_DIR)

            mapping_status = "No Conclusive Result"
            match_details_string = ""
            if dynamic_target_stats:
                matching_matches = find_matches_by_stats(combined_football_data, dynamic_target_stats)

                if not matching_matches.empty:
                    if len(matching_matches) == 1:
                        total_matches_found += 1
                        match_info = matching_matches.iloc[0]
                        mapping_status = (
                            f"{match_info['HomeTeam']} vs {match_info['AwayTeam']} on {match_info['Date']} "
                            f"(Season: {match_info['Season']})"
                        )
                        # Format the match details into a readable string
                        match_details = []
                        for col in display_cols_for_match:
                            if col in match_info: # Ensure column exists
                                match_details.append(f"{col}: {match_info[col]}")
                        match_details_string = "; ".join(match_details)
                    else:
                        # For multiple matches, just indicate count and first few
                        mapping_status = f"Multiple Matches Found ({len(matching_matches)}): "
                        first_matches_info = []
                        for i, match_info in matching_matches.head(3).iterrows():
                            first_matches_info.append(
                                f"{match_info['HomeTeam']} vs {match_info['AwayTeam']} on {match_info['Date']} (Season: {match_info['Season']})"
                            )
                        mapping_status += "; ".join(first_matches_info)
                        if len(matching_matches) > 3:
                            mapping_status += " and more..."
                        match_details_string = "N/A (Multiple Matches)" # Indicate no specific details for multiple
                else:
                    total_no_conclusive_result += 1
                    match_details_string = "N/A"
            else:
                total_no_conclusive_result += 1 # Count if sample file was not parsed correctly or not found
                match_details_string = "N/A (Sample parsing error or file not found)"

            results.append({
                'Sample #': sample_num,
                'Mapping': mapping_status,
                'Match Stats (Historical Data)': match_details_string
            })

        results_df = pd.DataFrame(results)

        print("\n--- Automated Match Mapping Results ---")
        try:
            from IPython.display import display
            display(results_df)
        except ImportError:
            # Use to_string() for console display to ensure full output
            print(results_df.to_string())

        print(f"\n--- Summary ---")
        print(f"Total samples processed: {total_samples_processed}")
        print(f"Total matches found (exactly one match per sample): {total_matches_found}")
        print(f"Total 'No Conclusive Result' samples: {total_no_conclusive_result}")

        # --- NEW CODE TO GENERATE 'final_df' ---
        print("\n--- Generating final_df with dataset.json mapping ---")
        id_mapping = {}
        try:
            with open(DATASET_JSON_PATH, 'r') as file:
                dataset = json.load(file)
            id_mapping = {entry['id']: entry for entry in dataset}
            print(f"Loaded {len(id_mapping)} entries from dataset.json for ID mapping.")
        except FileNotFoundError:
            print(f"Error: {DATASET_JSON_PATH} not found. Cannot perform ID mapping for final_df.")
        except json.JSONDecodeError:
            print(f"Error: Could not decode JSON from {DATASET_JSON_PATH}.")

        # Filter the results for rows with a value other than "No Conclusive Result"
        # Using the 'results' list generated earlier in this script
        filtered_results = [row for row in results if row['Mapping'] != "No Conclusive Result"]
        print(f"Filtered results (not 'No Conclusive Result'): {len(filtered_results)} rows.")

        # Get the first 275 rows
        selected_results = filtered_results[:275]
        print(f"Selected first 275 filtered results: {len(selected_results)} rows.")

        # Create a DataFrame with the selected rows and their corresponding IDs
        selected_data = []
        for result in selected_results:
            sample_id = result.get('Sample #') # Use .get() for safer access
            if sample_id is not None and sample_id in id_mapping:
                # Create a copy of the result dictionary to avoid modifying original
                # and then add the 'ID' from id_mapping
                row_data = result.copy()
                row_data['ID'] = id_mapping[sample_id]['id']
                selected_data.append(row_data)
            else:
                # Optional: print a message if a sample_id is not found in id_mapping
                if sample_id is not None:
                    print(f"Warning: Sample ID {sample_id} from results not found in dataset.json for final_df.")

        final_df = pd.DataFrame(selected_data)

        # Display the resulting DataFrame
        print("\n--- Head of final_df ---")
        try:
            from IPython.display import display
            display(final_df.head())
        except ImportError:
            print(final_df.head().to_string())

        print(f"\nFinal DataFrame 'final_df' has {len(final_df)} rows.")

Using main data directory: ./LiveSum_++/english-premier-league/
Using sample data directory: ./LiveSum_++/training_data/
CSV files to process (main data): ['2013-14.csv', '2014-15.csv', '2015-16.csv', '2016-17.csv', '2017-18.csv', '2018-19.csv', '2019-20.csv', '2020-21.csv', '2021-22.csv', '2022-23.csv', '2023-24.csv']

Loading and combining main Premier League data...

Successfully loaded 3840 rows of historical Premier League data.
First 5 rows of combined main data:

  Div      Date    HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  HTAG HTR      Referee  HS  AS  HST  AST  HF  AF  HC  AC  HY  AY  HR  AR  B365H  B365D  B365A   Season
0  E0  17/08/13     Arsenal  Aston Villa     1     3   A     1     1   D     A Taylor  16   9    4    4  15  18   4   3   4   5   1   0   1.44   4.75    8.0  2013-14
1  E0  17/08/13   Liverpool        Stoke     1     0   H     1     0   H   M Atkinson  26  10   11    4  11  11  12   6   1   1   0   0   1.40   5.00    9.5  2013-14
2  E0  17/08/13     Norwich      Everton     2     2   D     0     0   D     M Oliver   8  19    2    6  13  10   6   8   2   0   0   0   3.20   3.40    2.4  2013-14
3  E0  17/08/13  Sunderland       Fulham     0     1   A     0     0   D  N Swarbrick  20   5    3    1  14  14   6   1   0   3   0   0   2.30   3.40    3.4  2013-14
4  E0  17/08/13     Swansea   Man United     1     4   A     0     2   A       P Dowd  17  15    6    7  13  10   7   4   1   3   0   0   4.20   3.50    2.0  2013-14

--- Matching Sample Files to Historical Data ---

--- Automated Match Mapping Results ---

      Sample #                                            Mapping                      Match Stats (Historical Data)
0            1                               No Conclusive Result                                                N/A
1            2  Man United vs Tottenham on 01/01/14 (Season: 2...  Season: 2013-14; Date: 01/01/14; HomeTeam: Man...
2            3  West Brom vs Newcastle on 01/01/14 (Season: 20...  Season: 2013-14; Date: 01/01/14; HomeTeam: Wes...
3            4    Liverpool vs Hull on 01/01/14 (Season: 2013-14)  Season: 2013-14; Date: 01/01/14; HomeTeam: Liv...
4            5     Stoke vs Everton on 01/01/14 (Season: 2013-14)  Season: 2013-14; Date: 01/01/14; HomeTeam: Sto...
5            6  Swansea vs Man City on 01/01/14 (Season: 2013-14)  Season: 2013-14; Date: 01/01/14; HomeTeam: Swa...
6            7   Fulham vs West Ham on 01/01/14 (Season: 2013-14)  Season: 2013-14; Date: 01/01/14; HomeTeam: Ful...
7            8                               No Conclusive Result                                                N/A
8            9  Southampton vs West Brom on 11/01/14 (Season: ...  Season: 2013-14; Date: 11/01/14; HomeTeam: Sou...
9           10      Hull vs Chelsea on 11/01/14 (Season: 2013-14)  Season: 2013-14; Date: 11/01/14; HomeTeam: Hul...
10          11   Everton vs Norwich on 11/01/14 (Season: 2013-14)  Season: 2013-14; Date: 11/01/14; HomeTeam: Eve...
11          12  Man United vs Swansea on 11/01/14 (Season: 201...  Season: 2013-14; Date: 11/01/14; HomeTeam: Man...
12          13  Tottenham vs Crystal Palace on 11/01/14 (Seaso...  Season: 2013-14; Date: 11/01/14; HomeTeam: Tot...
13          14  Fulham vs Sunderland on 11/01/14 (Season: 2013...  Season: 2013-14; Date: 11/01/14; HomeTeam: Ful...
14          15   Stoke vs Liverpool on 12/01/14 (Season: 2013-14)  Season: 2013-14; Date: 12/01/14; HomeTeam: Sto...
15          16  Newcastle vs Man City on 12/01/14 (Season: 201...  Season: 2013-14; Date: 12/01/14; HomeTeam: New...
16          17                               No Conclusive Result                                                N/A
17          18  West Ham vs Newcastle on 18/01/14 (Season: 201...  Season: 2013-14; Date: 18/01/14; HomeTeam: Wes...
18          19  Man City vs Cardiff on 18/01/14 (Season: 2013-14)  Season: 2013-14; Date: 18/01/14; HomeTeam: Man...
19          20                               No Conclusive Result                                                N/A
20          21  Sunderland vs Southampton on 18/01/14 (Season:...  Season: 2013-14; Date: 18/01/14; HomeTeam: Sun...
21          22    Arsenal vs Fulham on 18/01/14 (Season: 2013-14)  Season: 2013-14; Date: 18/01/14; HomeTeam: Ars...
22          23  Crystal Palace vs Stoke on 18/01/14 (Season: 2...  Season: 2013-14; Date: 18/01/14; HomeTeam: Cry...
23          24  Chelsea vs Man United on 19/01/14 (Season: 201...  Season: 2013-14; Date: 19/01/14; HomeTeam: Che...
24          25  Swansea vs Tottenham on 19/01/14 (Season: 2013...  Season: 2013-14; Date: 19/01/14; HomeTeam: Swa...
25          26  West Brom vs Everton on 20/01/14 (Season: 2013...  Season: 2013-14; Date: 20/01/14; HomeTeam: Wes...
26          27  Norwich vs Newcastle on 28/01/14 (Season: 2013...  Season: 2013-14; Date: 28/01/14; HomeTeam: Nor...
27          28  Crystal Palace vs Hull on 28/01/14 (Season: 20...  Season: 2013-14; Date: 28/01/14; HomeTeam: Cry...
28          29  Liverpool vs Everton on 28/01/14 (Season: 2013...  Season: 2013-14; Date: 28/01/14; HomeTeam: Liv...
29          30                               No Conclusive Result                                                N/A
30          31    Swansea vs Fulham on 28/01/14 (Season: 2013-14)  Season: 2013-14; Date: 28/01/14; HomeTeam: Swa...
31          32  Man United vs Cardiff on 28/01/14 (Season: 201...  Season: 2013-14; Date: 28/01/14; HomeTeam: Man...
32          33                               No Conclusive Result                                                N/A
33          34  Tottenham vs Man City on 29/01/14 (Season: 201...  Season: 2013-14; Date: 29/01/14; HomeTeam: Tot...
34          35                               No Conclusive Result                                                N/A
35          36  Chelsea vs West Ham on 29/01/14 (Season: 2013-14)  Season: 2013-14; Date: 29/01/14; HomeTeam: Che...
36          37  West Ham vs Swansea on 01/02/14 (Season: 2013-14)  Season: 2013-14; Date: 01/02/14; HomeTeam: Wes...
37          38  Fulham vs Southampton on 01/02/14 (Season: 201...  Season: 2013-14; Date: 01/02/14; HomeTeam: Ful...
38          39  Stoke vs Man United on 01/02/14 (Season: 2013-14)  Season: 2013-14; Date: 01/02/14; HomeTeam: Sto...
39          40  Everton vs Aston Villa on 01/02/14 (Season: 20...  Season: 2013-14; Date: 01/02/14; HomeTeam: Eve...
40          41  Arsenal vs Crystal Palace on 02/02/14 (Season:...  Season: 2013-14; Date: 02/02/14; HomeTeam: Ars...
41          42  West Brom vs Liverpool on 02/02/14 (Season: 20...  Season: 2013-14; Date: 02/02/14; HomeTeam: Wes...
42          43  Man City vs Chelsea on 03/02/14 (Season: 2013-14)  Season: 2013-14; Date: 03/02/14; HomeTeam: Man...
43          44  Chelsea vs Newcastle on 08/02/14 (Season: 2013...  Season: 2013-14; Date: 08/02/14; HomeTeam: Che...
44          45  Liverpool vs Arsenal on 08/02/14 (Season: 2013...  Season: 2013-14; Date: 08/02/14; HomeTeam: Liv...
45          46  Southampton vs Stoke on 08/02/14 (Season: 2013...  Season: 2013-14; Date: 08/02/14; HomeTeam: Sou...
46          47  Aston Villa vs West Ham on 08/02/14 (Season: 2...  Season: 2013-14; Date: 08/02/14; HomeTeam: Ast...
47          48   Swansea vs Cardiff on 08/02/14 (Season: 2013-14)  Season: 2013-14; Date: 08/02/14; HomeTeam: Swa...
48          49  Norwich vs Man City on 08/02/14 (Season: 2013-14)  Season: 2013-14; Date: 08/02/14; HomeTeam: Nor...
49          50  Crystal Palace vs West Brom on 08/02/14 (Seaso...  Season: 2013-14; Date: 08/02/14; HomeTeam: Cry...
50          51  Man United vs Fulham on 09/02/14 (Season: 2013...  Season: 2013-14; Date: 09/02/14; HomeTeam: Man...
51          52  West Ham vs Norwich on 11/02/14 (Season: 2013-14)  Season: 2013-14; Date: 11/02/14; HomeTeam: Wes...
52          53  Hull vs Southampton on 11/02/14 (Season: 2013-14)  Season: 2013-14; Date: 11/02/14; HomeTeam: Hul...
53          54  West Brom vs Chelsea on 11/02/14 (Season: 2013...  Season: 2013-14; Date: 11/02/14; HomeTeam: Wes...
54          55  Cardiff vs Aston Villa on 11/02/14 (Season: 20...  Season: 2013-14; Date: 11/02/14; HomeTeam: Car...
55          56     Stoke vs Swansea on 12/02/14 (Season: 2013-14)  Season: 2013-14; Date: 12/02/14; HomeTeam: Sto...
56          57  Newcastle vs Tottenham on 12/02/14 (Season: 20...  Season: 2013-14; Date: 12/02/14; HomeTeam: New...
57          58  Arsenal vs Man United on 12/02/14 (Season: 201...  Season: 2013-14; Date: 12/02/14; HomeTeam: Ars...
58          59  Fulham vs Liverpool on 12/02/14 (Season: 2013-14)  Season: 2013-14; Date: 12/02/14; HomeTeam: Ful...
59          60  West Brom vs Fulham on 22/02/14 (Season: 2013-14)  Season: 2013-14; Date: 22/02/14; HomeTeam: Wes...
60          61                               No Conclusive Result                                                N/A
61          62      Cardiff vs Hull on 22/02/14 (Season: 2013-14)  Season: 2013-14; Date: 22/02/14; HomeTeam: Car...
62          63    Man City vs Stoke on 22/02/14 (Season: 2013-14)  Season: 2013-14; Date: 22/02/14; HomeTeam: Man...
63          64  West Ham vs Southampton on 22/02/14 (Season: 2...  Season: 2013-14; Date: 22/02/14; HomeTeam: Wes...
64          65  Newcastle vs Aston Villa on 23/02/14 (Season: ...  Season: 2013-14; Date: 23/02/14; HomeTeam: New...
65          66  Liverpool vs Swansea on 23/02/14 (Season: 2013...  Season: 2013-14; Date: 23/02/14; HomeTeam: Liv...
66          67  Southampton vs Liverpool on 01/03/14 (Season: ...  Season: 2013-14; Date: 01/03/14; HomeTeam: Sou...
67          68    Hull vs Newcastle on 01/03/14 (Season: 2013-14)  Season: 2013-14; Date: 01/03/14; HomeTeam: Hul...
68          69  Sunderland vs West Brom on 07/05/14 (Season: 2...  Season: 2013-14; Date: 07/05/14; HomeTeam: Sun...
69          70  Everton vs West Ham on 01/03/14 (Season: 2013-14)  Season: 2013-14; Date: 01/03/14; HomeTeam: Eve...
70          71                               No Conclusive Result                                                N/A
71          72  Tottenham vs Cardiff on 02/03/14 (Season: 2013...  Season: 2013-14; Date: 02/03/14; HomeTeam: Tot...
72          73    Cardiff vs Fulham on 08/03/14 (Season: 2013-14)  Season: 2013-14; Date: 08/03/14; HomeTeam: Car...
73          74   Arsenal vs Swansea on 25/03/14 (Season: 2013-14)  Season: 2013-14; Date: 25/03/14; HomeTeam: Ars...
74          75     Norwich vs Stoke on 08/03/14 (Season: 2013-14)  Season: 2013-14; Date: 08/03/14; HomeTeam: Nor...
75          76  Crystal Palace vs Southampton on 08/03/14 (Sea...  Season: 2013-14; Date: 08/03/14; HomeTeam: Cry...
76          77  Man City vs Aston Villa on 07/05/14 (Season: 2...  Season: 2013-14; Date: 07/05/14; HomeTeam: Man...
77          78  Newcastle vs Everton on 25/03/14 (Season: 2013...  Season: 2013-14; Date: 25/03/14; HomeTeam: New...
78          79  Fulham vs Newcastle on 15/03/14 (Season: 2013-14)  Season: 2013-14; Date: 15/03/14; HomeTeam: Ful...
79          80  Southampton vs Norwich on 15/03/14 (Season: 20...  Season: 2013-14; Date: 15/03/14; HomeTeam: Sou...
80          81   Everton vs Cardiff on 15/03/14 (Season: 2013-14)  Season: 2013-14; Date: 15/03/14; HomeTeam: Eve...
81          82     Hull vs Man City on 15/03/14 (Season: 2013-14)  Season: 2013-14; Date: 15/03/14; HomeTeam: Hul...
82          83                               No Conclusive Result                                                N/A
83          84  Sunderland vs Crystal Palace on 15/03/14 (Seas...  Season: 2013-14; Date: 15/03/14; HomeTeam: Sun...
84          85  Swansea vs West Brom on 15/03/14 (Season: 2013...  Season: 2013-14; Date: 15/03/14; HomeTeam: Swa...
85          86    Stoke vs West Ham on 15/03/14 (Season: 2013-14)  Season: 2013-14; Date: 15/03/14; HomeTeam: Sto...
86          87  Tottenham vs Arsenal on 16/03/14 (Season: 2013...  Season: 2013-14; Date: 16/03/14; HomeTeam: Tot...
87          88                               No Conclusive Result                                                N/A
88          89                               No Conclusive Result                                                N/A
89          90    Hull vs West Brom on 22/03/14 (Season: 2013-14)  Season: 2013-14; Date: 22/03/14; HomeTeam: Hul...
90          91  West Ham vs Man United on 22/03/14 (Season: 20...  Season: 2013-14; Date: 22/03/14; HomeTeam: Wes...
91          92   Everton vs Swansea on 22/03/14 (Season: 2013-14)  Season: 2013-14; Date: 22/03/14; HomeTeam: Eve...
92          93                               No Conclusive Result                                                N/A
93          94  Newcastle vs Crystal Palace on 22/03/14 (Seaso...  Season: 2013-14; Date: 22/03/14; HomeTeam: New...
94          95  Cardiff vs Liverpool on 22/03/14 (Season: 2013...  Season: 2013-14; Date: 22/03/14; HomeTeam: Car...
95          96   Chelsea vs Arsenal on 22/03/14 (Season: 2013-14)  Season: 2013-14; Date: 22/03/14; HomeTeam: Che...
96          97                               No Conclusive Result                                                N/A
97          98  Aston Villa vs Stoke on 23/03/14 (Season: 2013...  Season: 2013-14; Date: 23/03/14; HomeTeam: Ast...
98          99     West Ham vs Hull on 26/03/14 (Season: 2013-14)  Season: 2013-14; Date: 26/03/14; HomeTeam: Wes...
99         100  Liverpool vs Sunderland on 26/03/14 (Season: 2...  Season: 2013-14; Date: 26/03/14; HomeTeam: Liv...
100        101        Stoke vs Hull on 29/03/14 (Season: 2013-14)  Season: 2013-14; Date: 29/03/14; HomeTeam: Sto...
101        102  Southampton vs Newcastle on 29/03/14 (Season: ...  Season: 2013-14; Date: 29/03/14; HomeTeam: Sou...
102        103  Arsenal vs Man City on 29/03/14 (Season: 2013-14)  Season: 2013-14; Date: 29/03/14; HomeTeam: Ars...
103        104   Swansea vs Norwich on 29/03/14 (Season: 2013-14)  Season: 2013-14; Date: 29/03/14; HomeTeam: Swa...
104        105  West Brom vs Cardiff on 29/03/14 (Season: 2013...  Season: 2013-14; Date: 29/03/14; HomeTeam: Wes...
105        106  Man United vs Aston Villa on 29/03/14 (Season:...  Season: 2013-14; Date: 29/03/14; HomeTeam: Man...
106        107  Liverpool vs Tottenham on 30/03/14 (Season: 20...  Season: 2013-14; Date: 30/03/14; HomeTeam: Liv...
107        108                               No Conclusive Result                                                N/A
108        109  Everton vs Crystal Palace on 16/04/14 (Season:...  Season: 2013-14; Date: 16/04/14; HomeTeam: Eve...
109        110  Man City vs Sunderland on 16/04/14 (Season: 20...  Season: 2013-14; Date: 16/04/14; HomeTeam: Man...
110        111  Norwich vs West Brom on 05/04/14 (Season: 2013...  Season: 2013-14; Date: 05/04/14; HomeTeam: Nor...
111        112  Aston Villa vs Fulham on 05/04/14 (Season: 201...  Season: 2013-14; Date: 05/04/14; HomeTeam: Ast...
112        113  Cardiff vs Crystal Palace on 05/04/14 (Season:...  Season: 2013-14; Date: 05/04/14; HomeTeam: Car...
113        114  Newcastle vs Man United on 05/04/14 (Season: 2...  Season: 2013-14; Date: 05/04/14; HomeTeam: New...
114        115                               No Conclusive Result                                                N/A
115        116      Hull vs Swansea on 05/04/14 (Season: 2013-14)  Season: 2013-14; Date: 05/04/14; HomeTeam: Hul...
116        117   Everton vs Arsenal on 06/04/14 (Season: 2013-14)  Season: 2013-14; Date: 06/04/14; HomeTeam: Eve...
117        118  Tottenham vs Sunderland on 07/04/14 (Season: 2...  Season: 2013-14; Date: 07/04/14; HomeTeam: Tot...
118        119    Fulham vs Norwich on 12/04/14 (Season: 2013-14)  Season: 2013-14; Date: 12/04/14; HomeTeam: Ful...
119        120   Stoke vs Newcastle on 12/04/14 (Season: 2013-14)  Season: 2013-14; Date: 12/04/14; HomeTeam: Sto...
120        121  Southampton vs Cardiff on 12/04/14 (Season: 20...  Season: 2013-14; Date: 12/04/14; HomeTeam: Sou...
121        122  Crystal Palace vs Aston Villa on 12/04/14 (Sea...  Season: 2013-14; Date: 12/04/14; HomeTeam: Cry...
122        123                               No Conclusive Result                                                N/A
123        124                               No Conclusive Result                                                N/A
124        125                               No Conclusive Result                                                N/A
125        126  Liverpool vs Man City on 13/04/14 (Season: 201...  Season: 2013-14; Date: 13/04/14; HomeTeam: Liv...
126        127  Tottenham vs Fulham on 19/04/14 (Season: 2013-14)  Season: 2013-14; Date: 19/04/14; HomeTeam: Tot...
127        128  West Ham vs Crystal Palace on 19/04/14 (Season...  Season: 2013-14; Date: 19/04/14; HomeTeam: Wes...
128        129     Cardiff vs Stoke on 19/04/14 (Season: 2013-14)  Season: 2013-14; Date: 19/04/14; HomeTeam: Car...
129        130  Newcastle vs Swansea on 19/04/14 (Season: 2013...  Season: 2013-14; Date: 19/04/14; HomeTeam: New...
130        131  Aston Villa vs Southampton on 19/04/14 (Season...  Season: 2013-14; Date: 19/04/14; HomeTeam: Ast...
131        132  Chelsea vs Sunderland on 19/04/14 (Season: 201...  Season: 2013-14; Date: 19/04/14; HomeTeam: Che...
132        133  Everton vs Man United on 20/04/14 (Season: 201...  Season: 2013-14; Date: 20/04/14; HomeTeam: Eve...
133        134  Norwich vs Liverpool on 20/04/14 (Season: 2013...  Season: 2013-14; Date: 20/04/14; HomeTeam: Nor...
134        135  Man United vs Norwich on 26/04/14 (Season: 201...  Season: 2013-14; Date: 26/04/14; HomeTeam: Man...
135        136                               No Conclusive Result                                                N/A
136        137                               No Conclusive Result                                                N/A
137        138  West Brom vs West Ham on 26/04/14 (Season: 201...  Season: 2013-14; Date: 26/04/14; HomeTeam: Wes...
138        139  Sunderland vs Cardiff on 27/04/14 (Season: 201...  Season: 2013-14; Date: 27/04/14; HomeTeam: Sun...
139        140  Liverpool vs Chelsea on 27/04/14 (Season: 2013...  Season: 2013-14; Date: 27/04/14; HomeTeam: Liv...
140        141  Newcastle vs Cardiff on 03/05/14 (Season: 2013...  Season: 2013-14; Date: 03/05/14; HomeTeam: New...
141        142  Man United vs Sunderland on 03/05/14 (Season: ...  Season: 2013-14; Date: 03/05/14; HomeTeam: Man...
142        143  Everton vs Man City on 03/05/14 (Season: 2013-14)  Season: 2013-14; Date: 03/05/14; HomeTeam: Eve...
143        144  Aston Villa vs Hull on 03/05/14 (Season: 2013-14)  Season: 2013-14; Date: 03/05/14; HomeTeam: Ast...
144        145  West Ham vs Tottenham on 03/05/14 (Season: 201...  Season: 2013-14; Date: 03/05/14; HomeTeam: Wes...
145        146  Swansea vs Southampton on 03/05/14 (Season: 20...  Season: 2013-14; Date: 03/05/14; HomeTeam: Swa...
146        147   Chelsea vs Norwich on 04/05/14 (Season: 2013-14)  Season: 2013-14; Date: 04/05/14; HomeTeam: Che...
147        148   Man United vs Hull on 06/05/14 (Season: 2013-14)  Season: 2013-14; Date: 06/05/14; HomeTeam: Man...
148        149                               No Conclusive Result                                                N/A
149        150                               No Conclusive Result                                                N/A
150        151                               No Conclusive Result                                                N/A
151        152  Southampton vs Man United on 11/05/14 (Season:...  Season: 2013-14; Date: 11/05/14; HomeTeam: Sou...
152        153  Tottenham vs Aston Villa on 11/05/14 (Season: ...  Season: 2013-14; Date: 11/05/14; HomeTeam: Tot...
153        154  Sunderland vs Swansea on 11/05/14 (Season: 201...  Season: 2013-14; Date: 11/05/14; HomeTeam: Sun...
154        155  Man City vs West Ham on 11/05/14 (Season: 2013...  Season: 2013-14; Date: 11/05/14; HomeTeam: Man...
155        156  Stoke vs Aston Villa on 16/08/14 (Season: 2014...  Season: 2014-15; Date: 16/08/14; HomeTeam: Sto...
156        157  Man United vs Swansea on 16/08/14 (Season: 201...  Season: 2014-15; Date: 16/08/14; HomeTeam: Man...
157        158                               No Conclusive Result                                                N/A
158        159  West Brom vs Sunderland on 16/08/14 (Season: 2...  Season: 2014-15; Date: 16/08/14; HomeTeam: Wes...
159        160                               No Conclusive Result                                                N/A
160        161  Newcastle vs Man City on 17/08/14 (Season: 201...  Season: 2014-15; Date: 17/08/14; HomeTeam: New...
161        162                               No Conclusive Result                                                N/A
162        163   Everton vs Arsenal on 23/08/14 (Season: 2014-15)  Season: 2014-15; Date: 23/08/14; HomeTeam: Eve...
163        164  Southampton vs West Brom on 23/08/14 (Season: ...  Season: 2014-15; Date: 23/08/14; HomeTeam: Sou...
164        165  Chelsea vs Leicester on 23/08/14 (Season: 2014...  Season: 2014-15; Date: 23/08/14; HomeTeam: Che...
165        166  Crystal Palace vs West Ham on 23/08/14 (Season...  Season: 2014-15; Date: 23/08/14; HomeTeam: Cry...
166        167   Swansea vs Burnley on 23/08/14 (Season: 2014-15)  Season: 2014-15; Date: 23/08/14; HomeTeam: Swa...
167        168        Hull vs Stoke on 24/08/14 (Season: 2014-15)  Season: 2014-15; Date: 24/08/14; HomeTeam: Hul...
168        169                               No Conclusive Result                                                N/A

--- Summary ---
Total samples processed: 3771
Total matches found (exactly one match per sample): 2718
Total 'No Conclusive Result' samples: 1053

--- Generating final_df with dataset.json mapping ---
Loaded 3771 entries from dataset.json for ID mapping.
Filtered results (not 'No Conclusive Result'): 2718 rows.
Selected first 275 filtered results: 275 rows.
Warning: Sample ID 2 from results not found in dataset.json for final_df.
Warning: Sample ID 3 from results not found in dataset.json for final_df.
Warning: Sample ID 4 from results not found in dataset.json for final_df.
Warning: Sample ID 5 from results not found in dataset.json for final_df.
Warning: Sample ID 6 from results not found in dataset.json for final_df.
Warning: Sample ID 7 from results not found in dataset.json for final_df.
Warning: Sample ID 9 from results not found in dataset.json for final_df.
Warning: Sample ID 10 from results not found in dataset.json for final_df.
Warning: Sample ID 11 from results not found in dataset.json for final_df.
Warning: Sample ID 12 from results not found in dataset.json for final_df.
Warning: Sample ID 13 from results not found in dataset.json for final_df.
Warning: Sample ID 14 from results not found in dataset.json for final_df.
Warning: Sample ID 15 from results not found in dataset.json for final_df.
Warning: Sample ID 16 from results not found in dataset.json for final_df.
Warning: Sample ID 18 from results not found in dataset.json for final_df.
Warning: Sample ID 19 from results not found in dataset.json for final_df.
Warning: Sample ID 21 from results not found in dataset.json for final_df.
Warning: Sample ID 22 from results not found in dataset.json for final_df.
Warning: Sample ID 23 from results not found in dataset.json for final_df.
Warning: Sample ID 24 from results not found in dataset.json for final_df.
Warning: Sample ID 25 from results not found in dataset.json for final_df.
Warning: Sample ID 26 from results not found in dataset.json for final_df.
Warning: Sample ID 27 from results not found in dataset.json for final_df.
Warning: Sample ID 28 from results not found in dataset.json for final_df.
Warning: Sample ID 29 from results not found in dataset.json for final_df.
Warning: Sample ID 31 from results not found in dataset.json for final_df.
Warning: Sample ID 32 from results not found in dataset.json for final_df.
Warning: Sample ID 34 from results not found in dataset.json for final_df.
Warning: Sample ID 36 from results not found in dataset.json for final_df.
Warning: Sample ID 37 from results not found in dataset.json for final_df.
Warning: Sample ID 38 from results not found in dataset.json for final_df.
Warning: Sample ID 39 from results not found in dataset.json for final_df.
Warning: Sample ID 40 from results not found in dataset.json for final_df.
Warning: Sample ID 41 from results not found in dataset.json for final_df.
Warning: Sample ID 42 from results not found in dataset.json for final_df.
Warning: Sample ID 43 from results not found in dataset.json for final_df.
Warning: Sample ID 44 from results not found in dataset.json for final_df.
Warning: Sample ID 45 from results not found in dataset.json for final_df.
Warning: Sample ID 46 from results not found in dataset.json for final_df.
Warning: Sample ID 47 from results not found in dataset.json for final_df.
Warning: Sample ID 48 from results not found in dataset.json for final_df.
Warning: Sample ID 49 from results not found in dataset.json for final_df.
Warning: Sample ID 50 from results not found in dataset.json for final_df.
Warning: Sample ID 51 from results not found in dataset.json for final_df.
Warning: Sample ID 52 from results not found in dataset.json for final_df.
Warning: Sample ID 53 from results not found in dataset.json for final_df.
Warning: Sample ID 54 from results not found in dataset.json for final_df.
Warning: Sample ID 55 from results not found in dataset.json for final_df.
Warning: Sample ID 56 from results not found in dataset.json for final_df.
Warning: Sample ID 57 from results not found in dataset.json for final_df.
Warning: Sample ID 58 from results not found in dataset.json for final_df.
Warning: Sample ID 59 from results not found in dataset.json for final_df.
Warning: Sample ID 60 from results not found in dataset.json for final_df.
Warning: Sample ID 62 from results not found in dataset.json for final_df.
Warning: Sample ID 63 from results not found in dataset.json for final_df.
Warning: Sample ID 64 from results not found in dataset.json for final_df.
Warning: Sample ID 65 from results not found in dataset.json for final_df.
Warning: Sample ID 66 from results not found in dataset.json for final_df.
Warning: Sample ID 67 from results not found in dataset.json for final_df.
Warning: Sample ID 68 from results not found in dataset.json for final_df.
Warning: Sample ID 69 from results not found in dataset.json for final_df.
Warning: Sample ID 70 from results not found in dataset.json for final_df.
Warning: Sample ID 72 from results not found in dataset.json for final_df.
Warning: Sample ID 73 from results not found in dataset.json for final_df.
Warning: Sample ID 74 from results not found in dataset.json for final_df.
Warning: Sample ID 75 from results not found in dataset.json for final_df.
Warning: Sample ID 76 from results not found in dataset.json for final_df.
Warning: Sample ID 77 from results not found in dataset.json for final_df.
Warning: Sample ID 78 from results not found in dataset.json for final_df.
Warning: Sample ID 79 from results not found in dataset.json for final_df.
Warning: Sample ID 80 from results not found in dataset.json for final_df.
Warning: Sample ID 81 from results not found in dataset.json for final_df.
Warning: Sample ID 82 from results not found in dataset.json for final_df.
Warning: Sample ID 84 from results not found in dataset.json for final_df.
Warning: Sample ID 85 from results not found in dataset.json for final_df.
Warning: Sample ID 86 from results not found in dataset.json for final_df.
Warning: Sample ID 87 from results not found in dataset.json for final_df.
Warning: Sample ID 90 from results not found in dataset.json for final_df.
Warning: Sample ID 91 from results not found in dataset.json for final_df.
Warning: Sample ID 92 from results not found in dataset.json for final_df.
Warning: Sample ID 94 from results not found in dataset.json for final_df.
Warning: Sample ID 95 from results not found in dataset.json for final_df.
Warning: Sample ID 96 from results not found in dataset.json for final_df.
Warning: Sample ID 98 from results not found in dataset.json for final_df.
Warning: Sample ID 99 from results not found in dataset.json for final_df.
Warning: Sample ID 100 from results not found in dataset.json for final_df.
Warning: Sample ID 101 from results not found in dataset.json for final_df.
Warning: Sample ID 102 from results not found in dataset.json for final_df.
Warning: Sample ID 103 from results not found in dataset.json for final_df.
Warning: Sample ID 104 from results not found in dataset.json for final_df.
Warning: Sample ID 105 from results not found in dataset.json for final_df.
Warning: Sample ID 106 from results not found in dataset.json for final_df.
Warning: Sample ID 107 from results not found in dataset.json for final_df.
Warning: Sample ID 109 from results not found in dataset.json for final_df.
Warning: Sample ID 110 from results not found in dataset.json for final_df.
Warning: Sample ID 111 from results not found in dataset.json for final_df.
Warning: Sample ID 112 from results not found in dataset.json for final_df.
Warning: Sample ID 113 from results not found in dataset.json for final_df.
Warning: Sample ID 114 from results not found in dataset.json for final_df.
Warning: Sample ID 116 from results not found in dataset.json for final_df.
Warning: Sample ID 117 from results not found in dataset.json for final_df.
Warning: Sample ID 118 from results not found in dataset.json for final_df.
Warning: Sample ID 119 from results not found in dataset.json for final_df.
Warning: Sample ID 120 from results not found in dataset.json for final_df.
Warning: Sample ID 121 from results not found in dataset.json for final_df.
Warning: Sample ID 122 from results not found in dataset.json for final_df.
Warning: Sample ID 126 from results not found in dataset.json for final_df.
Warning: Sample ID 127 from results not found in dataset.json for final_df.
Warning: Sample ID 128 from results not found in dataset.json for final_df.
Warning: Sample ID 129 from results not found in dataset.json for final_df.
Warning: Sample ID 130 from results not found in dataset.json for final_df.
Warning: Sample ID 131 from results not found in dataset.json for final_df.
Warning: Sample ID 132 from results not found in dataset.json for final_df.
Warning: Sample ID 133 from results not found in dataset.json for final_df.
Warning: Sample ID 134 from results not found in dataset.json for final_df.
Warning: Sample ID 135 from results not found in dataset.json for final_df.
Warning: Sample ID 138 from results not found in dataset.json for final_df.
Warning: Sample ID 139 from results not found in dataset.json for final_df.
Warning: Sample ID 140 from results not found in dataset.json for final_df.
Warning: Sample ID 141 from results not found in dataset.json for final_df.
Warning: Sample ID 142 from results not found in dataset.json for final_df.
Warning: Sample ID 143 from results not found in dataset.json for final_df.
Warning: Sample ID 144 from results not found in dataset.json for final_df.
Warning: Sample ID 145 from results not found in dataset.json for final_df.
Warning: Sample ID 146 from results not found in dataset.json for final_df.
Warning: Sample ID 147 from results not found in dataset.json for final_df.
Warning: Sample ID 148 from results not found in dataset.json for final_df.
Warning: Sample ID 152 from results not found in dataset.json for final_df.
Warning: Sample ID 153 from results not found in dataset.json for final_df.
Warning: Sample ID 154 from results not found in dataset.json for final_df.
Warning: Sample ID 155 from results not found in dataset.json for final_df.
Warning: Sample ID 156 from results not found in dataset.json for final_df.
Warning: Sample ID 157 from results not found in dataset.json for final_df.
Warning: Sample ID 159 from results not found in dataset.json for final_df.
Warning: Sample ID 161 from results not found in dataset.json for final_df.
Warning: Sample ID 163 from results not found in dataset.json for final_df.
Warning: Sample ID 164 from results not found in dataset.json for final_df.
Warning: Sample ID 165 from results not found in dataset.json for final_df.
Warning: Sample ID 166 from results not found in dataset.json for final_df.
Warning: Sample ID 167 from results not found in dataset.json for final_df.
Warning: Sample ID 168 from results not found in dataset.json for final_df.
Warning: Sample ID 170 from results not found in dataset.json for final_df.
Warning: Sample ID 171 from results not found in dataset.json for final_df.
Warning: Sample ID 173 from results not found in dataset.json for final_df.
Warning: Sample ID 174 from results not found in dataset.json for final_df.
Warning: Sample ID 175 from results not found in dataset.json for final_df.
Warning: Sample ID 176 from results not found in dataset.json for final_df.
Warning: Sample ID 177 from results not found in dataset.json for final_df.
Warning: Sample ID 178 from results not found in dataset.json for final_df.
Warning: Sample ID 179 from results not found in dataset.json for final_df.
Warning: Sample ID 180 from results not found in dataset.json for final_df.
Warning: Sample ID 181 from results not found in dataset.json for final_df.
Warning: Sample ID 183 from results not found in dataset.json for final_df.
Warning: Sample ID 186 from results not found in dataset.json for final_df.
Warning: Sample ID 187 from results not found in dataset.json for final_df.
Warning: Sample ID 189 from results not found in dataset.json for final_df.
Warning: Sample ID 190 from results not found in dataset.json for final_df.
Warning: Sample ID 191 from results not found in dataset.json for final_df.
Warning: Sample ID 193 from results not found in dataset.json for final_df.
Warning: Sample ID 194 from results not found in dataset.json for final_df.
Warning: Sample ID 196 from results not found in dataset.json for final_df.
Warning: Sample ID 197 from results not found in dataset.json for final_df.
Warning: Sample ID 198 from results not found in dataset.json for final_df.
Warning: Sample ID 199 from results not found in dataset.json for final_df.
Warning: Sample ID 200 from results not found in dataset.json for final_df.
Warning: Sample ID 202 from results not found in dataset.json for final_df.
Warning: Sample ID 204 from results not found in dataset.json for final_df.
Warning: Sample ID 205 from results not found in dataset.json for final_df.
Warning: Sample ID 206 from results not found in dataset.json for final_df.
Warning: Sample ID 207 from results not found in dataset.json for final_df.
Warning: Sample ID 208 from results not found in dataset.json for final_df.
Warning: Sample ID 209 from results not found in dataset.json for final_df.
Warning: Sample ID 210 from results not found in dataset.json for final_df.
Warning: Sample ID 211 from results not found in dataset.json for final_df.
Warning: Sample ID 212 from results not found in dataset.json for final_df.
Warning: Sample ID 213 from results not found in dataset.json for final_df.
Warning: Sample ID 215 from results not found in dataset.json for final_df.
Warning: Sample ID 216 from results not found in dataset.json for final_df.
Warning: Sample ID 217 from results not found in dataset.json for final_df.
Warning: Sample ID 218 from results not found in dataset.json for final_df.
Warning: Sample ID 219 from results not found in dataset.json for final_df.
Warning: Sample ID 220 from results not found in dataset.json for final_df.
Warning: Sample ID 222 from results not found in dataset.json for final_df.
Warning: Sample ID 223 from results not found in dataset.json for final_df.
Warning: Sample ID 224 from results not found in dataset.json for final_df.
Warning: Sample ID 226 from results not found in dataset.json for final_df.
Warning: Sample ID 228 from results not found in dataset.json for final_df.
Warning: Sample ID 229 from results not found in dataset.json for final_df.
Warning: Sample ID 230 from results not found in dataset.json for final_df.
Warning: Sample ID 231 from results not found in dataset.json for final_df.
Warning: Sample ID 232 from results not found in dataset.json for final_df.
Warning: Sample ID 233 from results not found in dataset.json for final_df.
Warning: Sample ID 234 from results not found in dataset.json for final_df.
Warning: Sample ID 235 from results not found in dataset.json for final_df.
Warning: Sample ID 239 from results not found in dataset.json for final_df.
Warning: Sample ID 240 from results not found in dataset.json for final_df.
Warning: Sample ID 241 from results not found in dataset.json for final_df.
Warning: Sample ID 243 from results not found in dataset.json for final_df.
Warning: Sample ID 244 from results not found in dataset.json for final_df.
Warning: Sample ID 246 from results not found in dataset.json for final_df.
Warning: Sample ID 248 from results not found in dataset.json for final_df.
Warning: Sample ID 249 from results not found in dataset.json for final_df.
Warning: Sample ID 250 from results not found in dataset.json for final_df.
Warning: Sample ID 251 from results not found in dataset.json for final_df.
Warning: Sample ID 252 from results not found in dataset.json for final_df.
Warning: Sample ID 253 from results not found in dataset.json for final_df.
Warning: Sample ID 254 from results not found in dataset.json for final_df.
Warning: Sample ID 255 from results not found in dataset.json for final_df.
Warning: Sample ID 256 from results not found in dataset.json for final_df.
Warning: Sample ID 257 from results not found in dataset.json for final_df.
Warning: Sample ID 258 from results not found in dataset.json for final_df.
Warning: Sample ID 259 from results not found in dataset.json for final_df.
Warning: Sample ID 260 from results not found in dataset.json for final_df.
Warning: Sample ID 261 from results not found in dataset.json for final_df.
Warning: Sample ID 262 from results not found in dataset.json for final_df.
Warning: Sample ID 263 from results not found in dataset.json for final_df.
Warning: Sample ID 264 from results not found in dataset.json for final_df.
Warning: Sample ID 265 from results not found in dataset.json for final_df.
Warning: Sample ID 266 from results not found in dataset.json for final_df.
Warning: Sample ID 267 from results not found in dataset.json for final_df.
Warning: Sample ID 268 from results not found in dataset.json for final_df.
Warning: Sample ID 270 from results not found in dataset.json for final_df.
Warning: Sample ID 271 from results not found in dataset.json for final_df.
Warning: Sample ID 275 from results not found in dataset.json for final_df.
Warning: Sample ID 276 from results not found in dataset.json for final_df.
Warning: Sample ID 277 from results not found in dataset.json for final_df.
Warning: Sample ID 280 from results not found in dataset.json for final_df.
Warning: Sample ID 281 from results not found in dataset.json for final_df.
Warning: Sample ID 282 from results not found in dataset.json for final_df.
Warning: Sample ID 283 from results not found in dataset.json for final_df.
Warning: Sample ID 284 from results not found in dataset.json for final_df.
Warning: Sample ID 285 from results not found in dataset.json for final_df.
Warning: Sample ID 286 from results not found in dataset.json for final_df.
Warning: Sample ID 287 from results not found in dataset.json for final_df.
Warning: Sample ID 288 from results not found in dataset.json for final_df.
Warning: Sample ID 289 from results not found in dataset.json for final_df.
Warning: Sample ID 290 from results not found in dataset.json for final_df.
Warning: Sample ID 291 from results not found in dataset.json for final_df.
Warning: Sample ID 293 from results not found in dataset.json for final_df.
Warning: Sample ID 294 from results not found in dataset.json for final_df.
Warning: Sample ID 295 from results not found in dataset.json for final_df.
Warning: Sample ID 296 from results not found in dataset.json for final_df.
Warning: Sample ID 297 from results not found in dataset.json for final_df.
Warning: Sample ID 298 from results not found in dataset.json for final_df.
Warning: Sample ID 299 from results not found in dataset.json for final_df.
Warning: Sample ID 300 from results not found in dataset.json for final_df.
Warning: Sample ID 302 from results not found in dataset.json for final_df.
Warning: Sample ID 303 from results not found in dataset.json for final_df.
Warning: Sample ID 305 from results not found in dataset.json for final_df.
Warning: Sample ID 306 from results not found in dataset.json for final_df.
Warning: Sample ID 307 from results not found in dataset.json for final_df.
Warning: Sample ID 308 from results not found in dataset.json for final_df.
Warning: Sample ID 310 from results not found in dataset.json for final_df.
Warning: Sample ID 312 from results not found in dataset.json for final_df.
Warning: Sample ID 313 from results not found in dataset.json for final_df.
Warning: Sample ID 314 from results not found in dataset.json for final_df.
Warning: Sample ID 315 from results not found in dataset.json for final_df.
Warning: Sample ID 316 from results not found in dataset.json for final_df.
Warning: Sample ID 318 from results not found in dataset.json for final_df.

Empty DataFrame
Columns: []
Index: []

Final DataFrame 'final_df' has 0 rows.

In [2]:
import json

# Load the dataset.json file
with open('./LiveSum_++/dataset.json', 'r') as file:
    dataset = json.load(file)

# Create a dictionary mapping IDs to their corresponding data
id_mapping = {entry['id']: entry for entry in dataset}

# Filter the results for rows with a value other than "No Conclusive Result"
filtered_results = [row for row in results if row['Mapping'] != "No Conclusive Result"]

# Get the first 400 rows
selected_results = filtered_results[:400]

# Create a DataFrame with the selected rows and their corresponding IDs
selected_data = []
for result in selected_results:
    sample_id = result['Sample #']
    if sample_id in id_mapping:
        selected_data.append({
            'ID': id_mapping[sample_id]['id'],
            **result
        })

final_df = pd.DataFrame(selected_data)

# Display the resulting DataFrame
print(final_df.head())

Empty DataFrame
Columns: []
Index: []